// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
#include "editor/Editor.h"
#include "editor/Design.h"
#include "editor/ConcordScriptLanguage.h"

#include <windows.h>
#include <algorithm>
#include <cctype>
#include <cstdio>
#include <limits>
#include <regex>
#include <sstream>

namespace Concord::Editor {
namespace {
std::string FoldCase(std::string text)
{
    for(char& c:text)if(static_cast<unsigned char>(c)<128)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return text;
}
bool ContainsText(const std::string& text,const char* query)
{
    return !query[0] || FoldCase(text).find(FoldCase(query))!=std::string::npos;
}
bool IsGenerated(const std::filesystem::path& path)
{
    const auto name=FoldCase(Utf8Text(path.filename()));
    return (name=="scenelayout.cx" || name=="projectruntime.cx") && ReadText(path).starts_with("// Generated by Concord Editor.");
}
bool IsProjectFile(const std::filesystem::path& root,const std::filesystem::path& path)
{
    const auto canonicalRoot=std::filesystem::weakly_canonical(root);
    const auto canonicalFile=std::filesystem::weakly_canonical(path);
    auto part=canonicalFile.begin();
    for(const auto& expected:canonicalRoot) {
        if(part==canonicalFile.end() || CompareStringOrdinal(expected.c_str(),-1,part->c_str(),-1,TRUE)!=CSTR_EQUAL)return false;
        ++part;
    }
    return part!=canonicalFile.end();
}
bool HasDiagnostic(const std::string& line)
{
    const auto text=FoldCase(line);
    return text.find("error")!=std::string::npos || text.find("warning")!=std::string::npos || text.find("failed")!=std::string::npos;
}
std::string ValidScriptName(std::string name)
{
    if(name.size()>3 && FoldCase(name.substr(name.size()-3))==".cx")name.resize(name.size()-3);
    if(name.empty() || name.size()>100 || !(std::isalpha(static_cast<unsigned char>(name[0])) || name[0]=='_'))
        throw std::runtime_error("Start with a letter or underscore; use a ConcordScript identifier.");
    for(unsigned char c:name)if(c>=128 || !(std::isalnum(c) || c=='_'))
        throw std::runtime_error("Use letters, numbers and underscores. Folder paths are not allowed.");
    const auto folded=FoldCase(name);
    if(folded=="con" || folded=="prn" || folded=="aux" || folded=="nul" ||
       (folded.size()==4 && (folded.starts_with("com") || folded.starts_with("lpt")) && folded[3]>='1' && folded[3]<='9'))
        throw std::runtime_error("This name is reserved by Windows.");
    if(folded=="scenelayout" || folded=="projectruntime")throw std::runtime_error("SceneLayout.cx is generated by the scene editor; choose another name.");
    return name;
}
void WriteNewSource(const std::filesystem::path& path,const std::string& text)
{
    const HANDLE file=CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr);
    if(file==INVALID_HANDLE_VALUE) {
        if(GetLastError()==ERROR_FILE_EXISTS || GetLastError()==ERROR_ALREADY_EXISTS)
            throw std::runtime_error("A file with this name already exists. Existing source is never overwritten.");
        throw std::runtime_error("Cannot create source file (Windows error "+std::to_string(GetLastError())+").");
    }
    DWORD written=0;
    const bool okay=WriteFile(file,text.data(),static_cast<DWORD>(text.size()),&written,nullptr) && written==text.size() && FlushFileBuffers(file);
    CloseHandle(file);
    if(!okay) {
        DeleteFileW(path.c_str());
        throw std::runtime_error("Cannot finish writing the new script.");
    }
}
}

void Workspace::RefreshScriptFiles(bool force)
{
    if(m_scriptListProject!=m_project) {
        m_scriptListProject=m_project;m_scriptFiles.clear();m_openScripts.clear();m_selectedScriptTab.clear();
        m_scriptScanAt=-1;m_sourceFilter[0]=0;m_findVisible=false;m_consoleHiddenPrefix.clear();
    }
    if(!force && m_scriptScanAt>=0 && ImGui::GetTime()-m_scriptScanAt<2.0)return;
    m_scriptScanAt=ImGui::GetTime();
    std::vector<std::filesystem::path> files;
    if(!m_project.empty()) {
        auto iterator=std::filesystem::recursive_directory_iterator(m_project,std::filesystem::directory_options::skip_permission_denied);
        size_t visited=0;
        for(const auto end=std::filesystem::recursive_directory_iterator{};iterator!=end;++iterator) {
            const auto& entry=*iterator;
            if(++visited>20000)break;
            const auto name=FoldCase(Utf8Text(entry.path().filename()));
            if(entry.is_directory()) {
                if(entry.is_symlink() || iterator.depth()>=16 || name.starts_with(".") || name=="bin" || name=="node_modules" ||
                   name=="build" || name.starts_with("build-") || name=="cmakefiles")iterator.disable_recursion_pending();
                continue;
            }
            const auto extension=FoldCase(Utf8Text(entry.path().extension()));
            if(entry.is_regular_file() && (extension==".cx" || extension==".cpp" || extension==".h" || extension==".hpp" || extension==".scene" || extension==".yu" || name=="concord.project") && IsProjectFile(m_project,entry.path()))files.push_back(entry.path());
        }
    }
    std::sort(files.begin(),files.end(),[](const auto& a,const auto& b){return FoldCase(Utf8Text(a))<FoldCase(Utf8Text(b));});
    m_generatedScripts.clear();
    for(const auto& file:files)if(IsGenerated(file))m_generatedScripts.push_back(file);
    m_scriptFiles=std::move(files);
}

void Workspace::FileBrowser()
{
    if(ImGui::Begin("Project")) {
        Attempt([&]{RefreshScriptFiles();});
        Design::Image("folder",ImGui::GetFontSize());ImGui::SameLine();
        ImGui::TextUnformatted(Utf8Text(m_project.filename()).c_str());
        Design::Eyebrow("PROJECT FILES");
        ImGui::SetNextItemWidth(-1);
        ImGui::InputTextWithHint("##sourceFilter","Filter files...",m_sourceFilter,sizeof(m_sourceFilter));
        bool newScript=false;
        if(Design::Action("##newAsset","plus","New"))ImGui::OpenPopup("Create asset");
        if(ImGui::BeginPopup("Create asset")) {
            if(ImGui::MenuItem("Scene (.scene)"))RequestSceneFile(false);
            if(ImGui::MenuItem("UI document (.yu)")){m_uiDesigner.NewDocument();SwitchPage(3);}
            if(ImGui::MenuItem("ConcordScript (.cx)"))newScript=true;
            ImGui::EndPopup();
        }
        if(newScript){m_newScriptError.clear();ImGui::OpenPopup("New ConcordScript");}
        ImGui::SameLine();if(Design::Action("##refreshSources","rotate"))Attempt([&]{RefreshScriptFiles(true);});
        if(ImGui::IsItemHovered())ImGui::SetTooltip("Refresh source files");
        ImGui::Separator();
        ImGui::BeginChild("Sources",{0,-ImGui::GetTextLineHeightWithSpacing()*3},ImGuiChildFlags_None);
        size_t visible=0;
        for(const auto& file:m_scriptFiles) {
            const auto relative=Utf8Text(file.lexically_relative(m_project));
            if(!ContainsText(relative,m_sourceFilter))continue;
            ++visible;ImGui::PushID(relative.c_str());
            auto position=ImGui::GetCursorScreenPos();position.y+=3;
            const auto extension=file.extension();
            const bool generated=std::find(m_generatedScripts.begin(),m_generatedScripts.end(),file)!=m_generatedScripts.end();
            Design::Icon(extension==L".scene"?"cube":extension==L".yu"?"grid":generated?"code":"file",position,ImGui::GetFontSize(),ImGui::GetColorU32(generated?Design::Muted:Design::Accent));
            const auto label="    "+relative;
            const bool selected=extension==L".scene"?file==m_scenePath:extension==L".yu"?file==m_uiDesigner.Path():file==m_script;
            if(ImGui::Selectable(label.c_str(),selected,ImGuiSelectableFlags_None,{0,ImGui::GetFontSize()+6}))Attempt([&]{OpenAsset(file);});
            if(ImGui::BeginPopupContextItem()) {
                if(extension==L".scene" && ImGui::MenuItem("Set as initial scene"))Attempt([&]{auto settings=m_projectConfig;settings.startupScene=relative;ApplyProjectSettings(settings);m_status="Initial scene saved";});
                if(extension==L".yu" && ImGui::MenuItem("Set as startup UI"))Attempt([&]{auto settings=m_projectConfig;settings.startupUi=relative;ApplyProjectSettings(settings);m_status="Startup UI saved";});
                if(ImGui::MenuItem("Show folder"))RevealFolder(file.parent_path());
                ImGui::EndPopup();
            }
            if(ImGui::IsItemHovered())ImGui::SetTooltip("%s\n%s",Utf8Text(file).c_str(),generated?"Generated from project settings. Read only.":"Open in its editor workspace");
            ImGui::PopID();
        }
        if(!visible)ImGui::TextDisabled("No matching files");
        ImGui::EndChild();
        ImGui::Separator();
        ImGui::TextDisabled("%zu files",m_scriptFiles.size());
        ImGui::TextWrapped("Switching files saves your edits.");
        NewScriptDialog();
    }
    ImGui::End();
}

void Workspace::NewScriptDialog()
{
    ImGui::SetNextWindowSize({430,0},ImGuiCond_Appearing);
    if(!ImGui::BeginPopupModal("New ConcordScript",nullptr,ImGuiWindowFlags_AlwaysAutoResize))return;
    ImGui::TextWrapped("Create a ConcordScript class in the project folder.");
    if(ImGui::IsWindowAppearing())ImGui::SetKeyboardFocusHere();
    ImGui::SetNextItemWidth(-1);
    const bool enter=ImGui::InputText("##newScript",m_newScriptName,sizeof(m_newScriptName),ImGuiInputTextFlags_EnterReturnsTrue);
    ImGui::TextDisabled("Example: PlayerController.cx");
    if(!m_newScriptError.empty())ImGui::TextWrapped("%s",m_newScriptError.c_str());
    if(Design::Action("##createSource","plus","Create script",false,true) || enter) {
        try {
            const auto name=ValidScriptName(m_newScriptName);
            const auto file=m_project/Utf8Path(name+".cx");
            if(m_project.empty() || !std::filesystem::is_directory(m_project) || !IsProjectFile(m_project,file))
                throw std::runtime_error("Open a valid project before creating a script.");
            SaveScript();
            WriteNewSource(file,"// "+name+"\n\nclass "+name+"\n{\npublic:\n    static void Update(float deltaTime)\n    {\n    }\n};\n");
            RefreshScriptFiles(true);OpenScript(file);SwitchPage(2);m_focusSource=true;m_status="Created "+name+".cx";
            ImGui::CloseCurrentPopup();
        } catch(const std::exception& error) {m_newScriptError=error.what();}
    }
    ImGui::SameLine();if(ImGui::Button("Cancel"))ImGui::CloseCurrentPopup();
    ImGui::EndPopup();
}

void Workspace::Scripts()
{
    m_codeFocused=false;
    if(ImGui::Begin("ConcordScript",nullptr,m_scriptDirty?ImGuiWindowFlags_UnsavedDocument:0)) {
        if(!m_script.empty() && std::find(m_openScripts.begin(),m_openScripts.end(),m_script)==m_openScripts.end())m_openScripts.push_back(m_script);
        const auto requested=m_script;
        const bool externalSelection=m_selectedScriptTab!=m_script;
        std::filesystem::path selected,closed;
        if(ImGui::BeginTabBar("ScriptTabs",ImGuiTabBarFlags_Reorderable|ImGuiTabBarFlags_FittingPolicyScroll|ImGuiTabBarFlags_TabListPopupButton)) {
            for(const auto& file:m_openScripts) {
                bool open=true;const auto label=Utf8Text(file.filename())+"###"+Utf8Text(file);
                ImGuiTabItemFlags flags=(file==requested && m_scriptDirty)?ImGuiTabItemFlags_UnsavedDocument:0;
                if(externalSelection && file==requested)flags|=ImGuiTabItemFlags_SetSelected;
                if(ImGui::BeginTabItem(label.c_str(),m_openScripts.size()>1?&open:nullptr,flags)) {
                    if(!externalSelection || file==requested)selected=file;
                    ImGui::EndTabItem();
                }
                if(!open)closed=file;
            }
            ImGui::EndTabBar();
        }
        if(!selected.empty() && selected!=m_script)Attempt([&]{OpenScript(selected);m_focusSource=true;});
        if(!closed.empty())Attempt([&]{
            if(closed==m_script) {
                const auto replacement=std::find_if(m_openScripts.begin(),m_openScripts.end(),[&](const auto& file){return file!=closed;});
                if(replacement!=m_openScripts.end())OpenScript(*replacement);
            }
            std::erase(m_openScripts,closed);
        });
        m_selectedScriptTab=m_script;
        const bool readOnly=m_sourceSaved.starts_with("// Generated by Concord Editor.");
        m_code.SetReadOnly(readOnly);
        ImGui::BeginDisabled(readOnly || m_script.empty());
        if(Design::Action("##saveSource","save"))Attempt([&]{SaveScript();m_status="Source saved";});
        if(ImGui::IsItemHovered())ImGui::SetTooltip("Save source (Ctrl+S)");
        ImGui::SameLine();
        if(Design::Action("##undoSource","undo"))m_code.Undo();
        if(ImGui::IsItemHovered())ImGui::SetTooltip("Undo (Ctrl+Z)");
        ImGui::SameLine();
        if(Design::Action("##redoSource","redo"))m_code.Redo();
        if(ImGui::IsItemHovered())ImGui::SetTooltip("Redo (Ctrl+Y)");
        ImGui::EndDisabled();ImGui::SameLine();
        if(Design::Action("##copySource","copy"))m_code.Copy();
        if(ImGui::IsItemHovered())ImGui::SetTooltip("Copy selection (Ctrl+C)");
        ImGui::SameLine();
        if(Design::Action("##editSource","more"))ImGui::OpenPopup("Source edit actions");
        if(ImGui::IsItemHovered())ImGui::SetTooltip("Clipboard and edit actions");
        if(ImGui::BeginPopup("Source edit actions")) {
            if(ImGui::MenuItem("Copy","Ctrl+C"))m_code.Copy();
            ImGui::BeginDisabled(readOnly || m_script.empty());
            if(ImGui::MenuItem("Cut","Ctrl+X"))m_code.Cut();
            if(ImGui::MenuItem("Paste","Ctrl+V"))m_code.Paste();
            ImGui::EndDisabled();ImGui::EndPopup();
        }
        ImGui::SameLine();if(Design::Action("##findSourceButton","search","Find",m_findVisible)){m_findVisible=true;m_focusFind=true;}
        ImGui::SameLine();if(Design::Action("##goToSource","arrow","Go to")){m_goToLine=m_code.CursorLine();ImGui::OpenPopup("Go to source line");}
        const bool sourceFocused=ImGui::IsWindowFocused(ImGuiFocusedFlags_RootAndChildWindows);
        const auto& io=ImGui::GetIO();
        if(sourceFocused && io.KeyCtrl && ImGui::IsKeyPressed(ImGuiKey_F)){m_findVisible=true;m_focusFind=true;}
        if(sourceFocused && io.KeyCtrl && ImGui::IsKeyPressed(ImGuiKey_G)){m_goToLine=m_code.CursorLine();ImGui::OpenPopup("Go to source line");}
        if(sourceFocused && ImGui::IsKeyPressed(ImGuiKey_F3) && m_findText[0])m_findMissing=!m_code.FindNext(m_findText);
        if(readOnly){Design::Badge("GENERATED / READ ONLY");ImGui::SameLine();ImGui::TextDisabled("Edit objects in 3D.");}
        if(m_findVisible) {
            if(m_focusFind){ImGui::SetKeyboardFocusHere();m_focusFind=false;}
            ImGui::SetNextItemWidth(std::max(100.0f,ImGui::GetContentRegionAvail().x-160.0f));
            const std::string oldQuery=m_findText;
            const bool enter=ImGui::InputTextWithHint("##findSource","Find in this file...",m_findText,sizeof(m_findText),ImGuiInputTextFlags_EnterReturnsTrue);
            if(oldQuery!=m_findText)m_findMissing=false;
            ImGui::SameLine();const bool next=ImGui::Button("Next");
            if(enter || next)m_findMissing=!m_code.FindNext(m_findText);
            ImGui::SameLine();if(ImGui::Button("Close##find")){m_findVisible=false;m_focusSource=true;}
            if(m_findMissing && m_findText[0])ImGui::TextDisabled("No match in this file.");
        }
        if(ImGui::BeginPopup("Go to source line")) {
            if(ImGui::IsWindowAppearing())ImGui::SetKeyboardFocusHere();
            const bool go=ImGui::InputInt("Line",&m_goToLine,1,10,ImGuiInputTextFlags_EnterReturnsTrue);
            if(ImGui::Button("Go") || go){m_code.GoToLine(std::max(1,m_goToLine));m_focusSource=true;ImGui::CloseCurrentPopup();}
            ImGui::EndPopup();
        }
        ImGui::Separator();
        ImGui::BeginChild("SourceArea",{0,-ImGui::GetTextLineHeightWithSpacing()},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar);
        if(m_focusSource){ImGui::SetNextWindowFocus();m_focusSource=false;}
        auto& fonts=ImGui::GetIO().Fonts->Fonts;
        if(fonts.Size>1)ImGui::PushFont(fonts[1]);
        if(m_code.Render("Source"))m_scriptDirty=m_code.GetText()!=m_sourceSaved;
        const bool cpp=m_script.extension()==L".cpp" || m_script.extension()==L".h" || m_script.extension()==L".hpp";
        if(m_code.IsFocused() && !readOnly && !cpp && io.KeyCtrl && ImGui::IsKeyPressed(ImGuiKey_Space)) {
            const std::string text=m_code.GetText();
            const int line=m_code.CursorLine(),column=m_code.CursorColumn();
            size_t offset=0;
            for(int index=1;index<line && offset<text.size();++index) {
                const auto end=text.find('\n',offset);
                offset=end==std::string::npos?text.size():end+1;
            }
            offset=std::min(text.size(),offset+static_cast<size_t>(std::max(0,column-1)));
            const size_t end=offset;
            while(offset>0 && (std::isalnum(static_cast<unsigned char>(text[offset-1])) || text[offset-1]=='_'))--offset;
            m_completions=ConcordScriptCompletions(text,std::string_view(text).substr(offset,end-offset));
            m_completionVisible=!m_completions.empty();
        }
        if(fonts.Size>1)ImGui::PopFont();
        m_codeFocused=m_code.IsFocused();
        ImGui::EndChild();
        if(m_completionVisible) {
            ImGui::SetNextWindowSize({280,0},ImGuiCond_Appearing);
            if(ImGui::Begin("Completions##source",&m_completionVisible,ImGuiWindowFlags_AlwaysAutoResize|ImGuiWindowFlags_NoSavedSettings)) {
                for(const auto& match:m_completions)if(ImGui::Selectable(match.c_str())) {
                    m_code.Complete(match);m_scriptDirty=m_code.GetText()!=m_sourceSaved;m_completionVisible=false;
                }
            }
            ImGui::End();
        }
        ImGui::TextDisabled("Ln %d, Col %d  |  UTF-8  |  %s  |  %s",m_code.CursorLine(),m_code.CursorColumn(),cpp?"C++":"ConcordScript",readOnly?"Read only":m_scriptDirty?"Unsaved changes":"Saved");
    }
    ImGui::End();
}

void Workspace::NavigateDiagnostic(const std::string& line)
{
    static const std::regex diagnostic(R"(((?:[A-Za-z]:[\\/]|\\\\)[^\r\n]*?\.cx|[^\s:"'()]+\.cx)["']?[:(]([0-9]+))",std::regex::icase);
    std::smatch match;
    if(!std::regex_search(line,match,diagnostic))return;
    std::string name=match[1].str();
    const auto drive=name.find(":\\");const auto slashDrive=name.find(":/");
    const auto start=drive!=std::string::npos?drive:slashDrive;
    if(start!=std::string::npos && start>0)name=name.substr(start-1);
    while(!name.empty() && (std::isspace(static_cast<unsigned char>(name.front())) || name.front()=='\'' || name.front()=='"'))name.erase(name.begin());
    while(!name.empty() && (name.back()=='\'' || name.back()=='"'))name.pop_back();
    auto candidate=Utf8Path(name);
    if(candidate.is_absolute() && !IsProjectFile(m_project,candidate))throw std::runtime_error("Diagnostic refers to a source outside this project.");
    if(!candidate.is_absolute())candidate=m_project/candidate;
    if(!IsProjectFile(m_project,candidate) || !std::filesystem::is_regular_file(candidate)) {
        RefreshScriptFiles(true);
        const auto leaf=Utf8Path(name).filename();
        auto found=m_scriptFiles.end();
        for(auto it=m_scriptFiles.begin();it!=m_scriptFiles.end();++it) {
            if(it->filename()==leaf || line.find(Utf8Text(it->filename()))!=std::string::npos) {
                if(found!=m_scriptFiles.end())throw std::runtime_error("Diagnostic file name is ambiguous; open the source from Project.");
                found=it;
            }
        }
        if(found==m_scriptFiles.end())throw std::runtime_error("Diagnostic does not refer to a source file inside this project.");
        candidate=*found;
    }
    const auto number=std::stoll(match[2].str());
    if(number<=0 || number>std::numeric_limits<int>::max())throw std::runtime_error("Diagnostic line number is invalid.");
    OpenScript(candidate);m_code.SetError(static_cast<int>(number),line);m_code.GoToLine(static_cast<int>(number));
    SwitchPage(2);m_focusSource=true;ImGui::SetWindowFocus("ConcordScript");
}

void Workspace::Console()
{
    if(ImGui::Begin("Build output")) {
        const bool busy=m_process.Busy();
        ImGui::TextDisabled("%s",busy?"BUILD / RUN ACTIVE":"OUTPUT");ImGui::SameLine();
        if(ImGui::SmallButton("Clear")){m_consoleHiddenPrefix=m_process.Output();m_consoleRaw.clear();m_consoleLines.clear();}
        ImGui::SameLine();if(ImGui::SmallButton("Copy output"))ImGui::SetClipboardText(m_process.Output().c_str());
        ImGui::SameLine();ImGui::Checkbox("Follow",&m_outputFollow);
        ImGui::SameLine();ImGui::Checkbox("Errors / warnings",&m_outputErrorsOnly);
        ImGui::SetNextItemWidth(-1);ImGui::InputTextWithHint("##filterOutput","Filter output...",m_outputFilter,sizeof(m_outputFilter));
        auto output=m_process.Output();
        if(!m_consoleHiddenPrefix.empty()) {
            if(output.starts_with(m_consoleHiddenPrefix))output.erase(0,m_consoleHiddenPrefix.size());else m_consoleHiddenPrefix.clear();
        }
        const bool changed=output!=m_consoleRaw;
        if(changed) {
            m_consoleRaw=output;m_consoleLines.clear();std::istringstream input(output);std::string line;
            while(std::getline(input,line)){if(!line.empty() && line.back()=='\r')line.pop_back();m_consoleLines.push_back(std::move(line));}
        }
        std::vector<size_t> visible;
        for(size_t i=0;i<m_consoleLines.size();++i)if((!m_outputErrorsOnly || HasDiagnostic(m_consoleLines[i])) && ContainsText(m_consoleLines[i],m_outputFilter))visible.push_back(i);
        ImGui::BeginChild("OutputLines",{},ImGuiChildFlags_None,ImGuiWindowFlags_HorizontalScrollbar);
        if(visible.empty())ImGui::TextDisabled(m_consoleRaw.empty()?"Build or run the project to see output here.":"No matching output.");
        ImGuiListClipper clipper;clipper.Begin(static_cast<int>(visible.size()));
        while(clipper.Step())for(int row=clipper.DisplayStart;row<clipper.DisplayEnd;++row) {
            const auto index=visible[row];const auto& line=m_consoleLines[index];ImGui::PushID(static_cast<int>(index));
            const bool diagnostic=FoldCase(line).find(".cx")!=std::string::npos;
            if(HasDiagnostic(line))ImGui::PushStyleColor(ImGuiCol_Text,ImVec4{0.97f,0.64f,0.43f,1});
            if(diagnostic) {
                if(ImGui::Selectable(line.c_str(),false,ImGuiSelectableFlags_None,{std::max(ImGui::GetContentRegionAvail().x,ImGui::CalcTextSize(line.c_str()).x),0}))
                    Attempt([&]{NavigateDiagnostic(line);});
                if(ImGui::IsItemHovered())ImGui::SetTooltip("Open diagnostic in ConcordScript");
            } else ImGui::TextUnformatted(line.c_str());
            if(HasDiagnostic(line))ImGui::PopStyleColor();
            ImGui::PopID();
        }
        if(changed && m_outputFollow)ImGui::SetScrollHereY(1.0f);
        ImGui::EndChild();
    }
    ImGui::End();
}
}
