// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
#include "editor/Editor.h"
#include "editor/Design.h"
#include "editor/Localization.h"
#include "editor/ConcordScriptLanguage.h"

#include <windows.h>
#include <algorithm>
#include <cctype>
#include <cstdio>
#include <limits>
#include <regex>
#include <sstream>

namespace Concord::Editor {
namespace {
std::string FoldCase(std::string text)
{
    for(char& c:text)if(static_cast<unsigned char>(c)<128)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return text;
}
bool ContainsText(const std::string& text,const char* query)
{
    return !query[0] || FoldCase(text).find(FoldCase(query))!=std::string::npos;
}
bool IsGenerated(const std::filesystem::path& path)
{
    const auto name=FoldCase(Utf8Text(path.filename()));
    return (name=="scenelayout.cx" || name=="projectruntime.cx") && ReadText(path).starts_with("// Generated by Concord Editor.");
}
bool IsProjectFile(const std::filesystem::path& root,const std::filesystem::path& path)
{
    const auto canonicalRoot=std::filesystem::weakly_canonical(root);
    const auto canonicalFile=std::filesystem::weakly_canonical(path);
    auto part=canonicalFile.begin();
    for(const auto& expected:canonicalRoot) {
        if(part==canonicalFile.end() || CompareStringOrdinal(expected.c_str(),-1,part->c_str(),-1,TRUE)!=CSTR_EQUAL)return false;
        ++part;
    }
    return part!=canonicalFile.end();
}
bool HasDiagnostic(const std::string& line)
{
    const auto text=FoldCase(line);
    return text.find("error")!=std::string::npos || text.find("warning")!=std::string::npos || text.find("failed")!=std::string::npos;
}
std::string ValidScriptName(std::string name)
{
    if(name.size()>3 && FoldCase(name.substr(name.size()-3))==".cx")name.resize(name.size()-3);
    if(name.empty() || name.size()>100 || !(std::isalpha(static_cast<unsigned char>(name[0])) || name[0]=='_'))
        throw std::runtime_error(Tr("Start with a letter or underscore; use a ConcordScript identifier."));
    for(unsigned char c:name)if(c>=128 || !(std::isalnum(c) || c=='_'))
        throw std::runtime_error(Tr("Use letters, numbers and underscores. Folder paths are not allowed."));
    const auto folded=FoldCase(name);
    if(folded=="con" || folded=="prn" || folded=="aux" || folded=="nul" ||
       (folded.size()==4 && (folded.starts_with("com") || folded.starts_with("lpt")) && folded[3]>='1' && folded[3]<='9'))
        throw std::runtime_error(Tr("This name is reserved by Windows."));
    if(folded=="scenelayout" || folded=="projectruntime")throw std::runtime_error(Tr("This name is used by a generated file; choose another name."));
    return name;
}
void WriteNewSource(const std::filesystem::path& path,const std::string& text)
{
    const HANDLE file=CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr);
    if(file==INVALID_HANDLE_VALUE) {
        if(GetLastError()==ERROR_FILE_EXISTS || GetLastError()==ERROR_ALREADY_EXISTS)
            throw std::runtime_error(Tr("A file with this name already exists. Existing source is never overwritten."));
        throw std::runtime_error("Cannot create source file (Windows error "+std::to_string(GetLastError())+").");
    }
    DWORD written=0;
    const bool okay=WriteFile(file,text.data(),static_cast<DWORD>(text.size()),&written,nullptr) && written==text.size() && FlushFileBuffers(file);
    CloseHandle(file);
    if(!okay) {
        DeleteFileW(path.c_str());
        throw std::runtime_error(Tr("Cannot finish writing the new script."));
    }
}
const char* FileIcon(const std::filesystem::path& file,bool generated)
{
    const auto extension=FoldCase(Utf8Text(file.extension()));
    if(extension==".scene")return "cube";
    if(extension==".yu")return "grid";
    if(extension==".project")return "settings";
    return generated?"code":"file";
}
}

void Workspace::RefreshScriptFiles(bool force)
{
    if(m_scriptListProject!=m_project) {
        m_scriptListProject=m_project;m_scriptFiles.clear();m_openScripts.clear();m_selectedScriptTab.clear();
        m_scriptScanAt=-1;m_sourceFilter[0]=0;m_findVisible=false;m_consoleHiddenPrefix.clear();
    }
    if(!force && m_scriptScanAt>=0 && ImGui::GetTime()-m_scriptScanAt<2.0)return;
    m_scriptScanAt=ImGui::GetTime();
    std::vector<std::filesystem::path> files;
    if(!m_project.empty()) {
        auto iterator=std::filesystem::recursive_directory_iterator(m_project,std::filesystem::directory_options::skip_permission_denied);
        size_t visited=0;
        for(const auto end=std::filesystem::recursive_directory_iterator{};iterator!=end;++iterator) {
            const auto& entry=*iterator;
            if(++visited>20000)break;
            const auto name=FoldCase(Utf8Text(entry.path().filename()));
            if(entry.is_directory()) {
                if(entry.is_symlink() || iterator.depth()>=16 || name.starts_with(".") || name=="bin" || name=="node_modules" ||
                   name=="build" || name.starts_with("build-") || name=="cmakefiles")iterator.disable_recursion_pending();
                continue;
            }
            const auto extension=FoldCase(Utf8Text(entry.path().extension()));
            if(entry.is_regular_file() && (extension==".cx" || extension==".cpp" || extension==".h" || extension==".hpp" || extension==".scene" || extension==".yu" || name=="concord.project") && IsProjectFile(m_project,entry.path()))files.push_back(entry.path());
        }
    }
    std::sort(files.begin(),files.end(),[](const auto& a,const auto& b){return FoldCase(Utf8Text(a))<FoldCase(Utf8Text(b));});
    m_generatedScripts.clear();
    for(const auto& file:files)if(IsGenerated(file))m_generatedScripts.push_back(file);
    m_scriptFiles=std::move(files);
}

void Workspace::FileBrowser()
{
    if(ImGui::Begin(TrId("Project").c_str())) {
        Attempt([&]{RefreshScriptFiles();});
        const float unit=ImGui::GetFontSize(),frame=ImGui::GetFrameHeight(),spacing=ImGui::GetStyle().ItemSpacing.x;
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x-(frame+spacing)*2);
        ImGui::InputTextWithHint("##sourceFilter",Tr("Search files..."),m_sourceFilter,sizeof(m_sourceFilter));
        bool newScript=false;
        ImGui::SameLine();if(Design::Action("Create","plus"))ImGui::OpenPopup("##createAsset");
        if(ImGui::BeginPopup("##createAsset")) {
            if(ImGui::MenuItem(Tr("Scene (.scene)")))RequestSceneFile(false);
            if(ImGui::MenuItem(Tr("UI document (.yu)"))){m_uiDesigner.NewDocument();SwitchPage(3);}
            if(ImGui::MenuItem(Tr("ConcordScript (.cx)")))newScript=true;
            ImGui::EndPopup();
        }
        if(newScript){m_newScriptError.clear();ImGui::OpenPopup("###NewScript");}
        ImGui::SameLine();if(Design::Action("Refresh","rotate"))Attempt([&]{RefreshScriptFiles(true);});
        ImGui::Spacing();
        Design::Image("folder",unit*0.95f,ImGui::GetColorU32(Design::Accent));ImGui::SameLine();
        ImGui::TextUnformatted(Utf8Text(m_project.filename()).c_str());
        ImGui::SameLine();ImGui::TextColored(Design::Muted,"%zu",m_scriptFiles.size());
        if(ImGui::BeginChild("##sources",{0,0},ImGuiChildFlags_None)) {
            size_t visible=0;
            const float row=std::round(unit*1.4f);
            for(const auto& file:m_scriptFiles) {
                const auto relative=Utf8Text(file.lexically_relative(m_project));
                if(!ContainsText(relative,m_sourceFilter))continue;
                ++visible;ImGui::PushID(relative.c_str());
                const auto position=ImGui::GetCursorScreenPos();
                const auto extension=FoldCase(Utf8Text(file.extension()));
                const bool generated=std::find(m_generatedScripts.begin(),m_generatedScripts.end(),file)!=m_generatedScripts.end();
                const bool selected=extension==".scene"?file==m_scenePath:extension==".yu"?file==m_uiDesigner.Path():file==m_script;
                if(ImGui::Selectable("##file",selected,ImGuiSelectableFlags_None,{0,row}))Attempt([&]{OpenAsset(file);});
                if(ImGui::BeginPopupContextItem()) {
                    if(ImGui::MenuItem(Tr("Open")))Attempt([&]{OpenAsset(file);});
                    if(extension==".scene" && ImGui::MenuItem(Tr("Set as initial scene")))Attempt([&]{auto settings=m_projectConfig;settings.startupScene=relative;ApplyProjectSettings(settings);m_status=Tr("Initial scene saved");});
                    if(extension==".yu" && ImGui::MenuItem(Tr("Set as startup UI")))Attempt([&]{auto settings=m_projectConfig;settings.startupUi=relative;ApplyProjectSettings(settings);m_status=Tr("Startup UI saved");});
                    ImGui::Separator();
                    if(ImGui::MenuItem(Tr("Show in Explorer")))RevealFolder(file.parent_path());
                    if(ImGui::MenuItem(Tr("Copy path")))ImGui::SetClipboardText(Utf8Text(file).c_str());
                    ImGui::EndPopup();
                }
                if(ImGui::IsItemHovered(ImGuiHoveredFlags_ForTooltip))
                    ImGui::SetTooltip("%s\n%s",Utf8Text(file).c_str(),generated?Tr("Generated from project settings. Read only."):Tr("Click to open in its workspace"));
                const ImU32 tint=generated?ImGui::GetColorU32(Design::Muted):extension==".scene"?IM_COL32(118,176,236,255):extension==".yu"?IM_COL32(140,196,168,255):ImGui::GetColorU32({0.78f,0.80f,0.84f,1});
                Design::Icon(FileIcon(file,generated),{position.x+unit*0.15f,position.y+(row-unit*0.95f)*0.5f},unit*0.95f,tint);
                ImGui::GetWindowDrawList()->AddText({position.x+unit*1.4f,position.y+(row-unit)*0.5f},
                    ImGui::GetColorU32(generated?ImGuiCol_TextDisabled:ImGuiCol_Text),relative.c_str());
                ImGui::PopID();
            }
            if(!visible)ImGui::TextColored(Design::Muted,"%s",Tr("No matching files"));
        }
        ImGui::EndChild();
        NewScriptDialog();
    }
    ImGui::End();
}

void Workspace::NewScriptDialog()
{
    if(!Design::BeginDialog(TrId("New ConcordScript","NewScript").c_str(),26))return;
    Design::Heading(Tr("New ConcordScript"));
    ImGui::TextColored(Design::Muted,"%s",Tr("Creates a ConcordScript class in the project folder."));
    ImGui::Spacing();
    if(ImGui::IsWindowAppearing())ImGui::SetKeyboardFocusHere();
    ImGui::SetNextItemWidth(-FLT_MIN);
    const bool enter=ImGui::InputText("##newScript",m_newScriptName,sizeof(m_newScriptName),ImGuiInputTextFlags_EnterReturnsTrue);
    ImGui::TextColored(Design::Muted,"%s",Tr("Example: PlayerController.cx"));
    if(!m_newScriptError.empty()){ImGui::PushTextWrapPos();ImGui::TextColored({0.96f,0.55f,0.45f,1},"%s",m_newScriptError.c_str());ImGui::PopTextWrapPos();}
    ImGui::Spacing();
    Design::AlignRight(Design::ButtonWidth(Tr("Cancel"),false)+Design::ButtonWidth(Tr("Create script"))+ImGui::GetStyle().ItemSpacing.x);
    if(Design::Action("##cancelScript","",Tr("Cancel")))ImGui::CloseCurrentPopup();
    ImGui::SameLine();
    if(Design::Action("##createSource","plus",Tr("Create script"),false,true) || enter) {
        try {
            const auto name=ValidScriptName(m_newScriptName);
            const auto file=m_project/Utf8Path(name+".cx");
            if(m_project.empty() || !std::filesystem::is_directory(m_project) || !IsProjectFile(m_project,file))
                throw std::runtime_error(Tr("Open a valid project before creating a script."));
            SaveScript();
            WriteNewSource(file,"// "+name+"\n\nclass "+name+"\n{\npublic:\n    static void Update(float deltaTime)\n    {\n    }\n};\n");
            RefreshScriptFiles(true);OpenScript(file);SwitchPage(2);m_focusSource=true;m_status=std::string(Tr("Created"))+" "+name+".cx";
            ImGui::CloseCurrentPopup();
        } catch(const std::exception& error) {m_newScriptError=error.what();}
    }
    ImGui::EndPopup();
}

void Workspace::Scripts()
{
    m_codeFocused=false;
    if(ImGui::Begin(TrId("ConcordScript","ConcordScript").c_str(),nullptr,m_scriptDirty?ImGuiWindowFlags_UnsavedDocument:0)) {
        if(!m_script.empty() && std::find(m_openScripts.begin(),m_openScripts.end(),m_script)==m_openScripts.end())m_openScripts.push_back(m_script);
        const auto requested=m_script;
        const bool externalSelection=m_selectedScriptTab!=m_script;
        std::filesystem::path selected,closed;
        if(ImGui::BeginTabBar("ScriptTabs",ImGuiTabBarFlags_Reorderable|ImGuiTabBarFlags_FittingPolicyScroll|ImGuiTabBarFlags_TabListPopupButton)) {
            for(const auto& file:m_openScripts) {
                bool open=true;const auto label=Utf8Text(file.filename())+"###"+Utf8Text(file);
                ImGuiTabItemFlags flags=(file==requested && m_scriptDirty)?ImGuiTabItemFlags_UnsavedDocument:0;
                if(externalSelection && file==requested)flags|=ImGuiTabItemFlags_SetSelected;
                if(ImGui::BeginTabItem(label.c_str(),m_openScripts.size()>1?&open:nullptr,flags)) {
                    if(!externalSelection || file==requested)selected=file;
                    ImGui::EndTabItem();
                }
                if(!open)closed=file;
            }
            ImGui::EndTabBar();
        }
        if(!selected.empty() && selected!=m_script)Attempt([&]{OpenScript(selected);m_focusSource=true;});
        if(!closed.empty())Attempt([&]{
            if(closed==m_script) {
                const auto replacement=std::find_if(m_openScripts.begin(),m_openScripts.end(),[&](const auto& file){return file!=closed;});
                if(replacement!=m_openScripts.end())OpenScript(*replacement);
            }
            std::erase(m_openScripts,closed);
        });
        m_selectedScriptTab=m_script;
        const bool readOnly=m_sourceSaved.starts_with("// Generated by Concord Editor.");
        m_code.SetReadOnly(readOnly);
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing,{ImGui::GetFontSize()*0.15f,ImGui::GetStyle().ItemSpacing.y});
        ImGui::BeginDisabled(readOnly || m_script.empty());
        if(Design::Ghost("Save source (Ctrl+S)","save"))Attempt([&]{SaveScript();m_status=Tr("Source saved");});
        ImGui::SameLine();if(Design::Ghost("Undo (Ctrl+Z)","undo"))m_code.Undo();
        ImGui::SameLine();if(Design::Ghost("Redo (Ctrl+Y)","redo"))m_code.Redo();
        ImGui::EndDisabled();
        ImGui::SameLine();if(Design::Ghost("Copy selection (Ctrl+C)","copy"))m_code.Copy();
        ImGui::SameLine();if(Design::Ghost("Clipboard and edit actions","more"))ImGui::OpenPopup("##sourceEdit");
        if(ImGui::BeginPopup("##sourceEdit")) {
            if(ImGui::MenuItem(Tr("Copy"),"Ctrl+C"))m_code.Copy();
            ImGui::BeginDisabled(readOnly || m_script.empty());
            if(ImGui::MenuItem(Tr("Cut"),"Ctrl+X"))m_code.Cut();
            if(ImGui::MenuItem(Tr("Paste"),"Ctrl+V"))m_code.Paste();
            ImGui::EndDisabled();ImGui::EndPopup();
        }
        ImGui::SameLine();if(Design::Ghost("##findSourceButton","search",Tr("Find"),m_findVisible)){m_findVisible=true;m_focusFind=true;}
        ImGui::SameLine();if(Design::Ghost("##goToSource","arrow",Tr("Go to line"))){m_goToLine=m_code.CursorLine();ImGui::OpenPopup("##goToLine");}
        ImGui::PopStyleVar();
        const bool sourceFocused=ImGui::IsWindowFocused(ImGuiFocusedFlags_RootAndChildWindows);
        const auto& io=ImGui::GetIO();
        if(sourceFocused && io.KeyCtrl && ImGui::IsKeyPressed(ImGuiKey_F)){m_findVisible=true;m_focusFind=true;}
        if(sourceFocused && io.KeyCtrl && ImGui::IsKeyPressed(ImGuiKey_G)){m_goToLine=m_code.CursorLine();ImGui::OpenPopup("##goToLine");}
        if(sourceFocused && ImGui::IsKeyPressed(ImGuiKey_F3) && m_findText[0])m_findMissing=!m_code.FindNext(m_findText);
        if(readOnly){ImGui::SameLine();Design::Badge(Tr("GENERATED / READ ONLY"));ImGui::SameLine();ImGui::TextColored(Design::Muted,"%s",Tr("Edit objects in the 3D workspace."));}
        if(m_findVisible) {
            if(m_focusFind){ImGui::SetKeyboardFocusHere();m_focusFind=false;}
            ImGui::SetNextItemWidth(std::max(100.0f,ImGui::GetContentRegionAvail().x-ImGui::GetFontSize()*9));
            const std::string oldQuery=m_findText;
            const bool enter=ImGui::InputTextWithHint("##findSource",Tr("Find in this file..."),m_findText,sizeof(m_findText),ImGuiInputTextFlags_EnterReturnsTrue);
            if(oldQuery!=m_findText)m_findMissing=false;
            ImGui::SameLine();const bool next=Design::Action("##findNext","",Tr("Next"));
            if(enter || next)m_findMissing=!m_code.FindNext(m_findText);
            ImGui::SameLine();if(Design::Ghost("Close search","close")){m_findVisible=false;m_focusSource=true;}
            if(m_findMissing && m_findText[0])ImGui::TextColored(Design::Muted,"%s",Tr("No match in this file."));
        }
        if(ImGui::BeginPopup("##goToLine")) {
            if(ImGui::IsWindowAppearing())ImGui::SetKeyboardFocusHere();
            const bool go=ImGui::InputInt(Tr("Line"),&m_goToLine,1,10,ImGuiInputTextFlags_EnterReturnsTrue);
            if(Design::Action("##go","arrow",Tr("Go")) || go){m_code.GoToLine(std::max(1,m_goToLine));m_focusSource=true;ImGui::CloseCurrentPopup();}
            ImGui::EndPopup();
        }
        ImGui::PushStyleColor(ImGuiCol_ChildBg,ImVec4{0.047f,0.047f,0.052f,1.0f});
        ImGui::PushStyleVar(ImGuiStyleVar_ChildRounding,ImGui::GetStyle().FrameRounding);
        ImGui::BeginChild("SourceArea",{0,-ImGui::GetTextLineHeightWithSpacing()},ImGuiChildFlags_Borders,ImGuiWindowFlags_NoScrollbar);
        if(m_focusSource){ImGui::SetNextWindowFocus();m_focusSource=false;}
        auto& fonts=ImGui::GetIO().Fonts->Fonts;
        if(fonts.Size>1)ImGui::PushFont(fonts[1]);
        if(m_code.Render("Source"))m_scriptDirty=m_code.GetText()!=m_sourceSaved;
        const bool cpp=m_script.extension()==L".cpp" || m_script.extension()==L".h" || m_script.extension()==L".hpp";
        if(m_code.IsFocused() && !readOnly && !cpp && io.KeyCtrl && ImGui::IsKeyPressed(ImGuiKey_Space)) {
            const std::string text=m_code.GetText();
            const int line=m_code.CursorLine(),column=m_code.CursorColumn();
            size_t offset=0;
            for(int index=1;index<line && offset<text.size();++index) {
                const auto end=text.find('\n',offset);
                offset=end==std::string::npos?text.size():end+1;
            }
            offset=std::min(text.size(),offset+static_cast<size_t>(std::max(0,column-1)));
            const size_t end=offset;
            while(offset>0 && (std::isalnum(static_cast<unsigned char>(text[offset-1])) || text[offset-1]=='_'))--offset;
            m_completions=ConcordScriptCompletions(text,std::string_view(text).substr(offset,end-offset));
            m_completionVisible=!m_completions.empty();
        }
        if(fonts.Size>1)ImGui::PopFont();
        m_codeFocused=m_code.IsFocused();
        ImGui::EndChild();
        ImGui::PopStyleVar();
        ImGui::PopStyleColor();
        if(m_completionVisible) {
            ImGui::SetNextWindowSize({280,0},ImGuiCond_Appearing);
            if(ImGui::Begin(TrId("Completions","Completions").c_str(),&m_completionVisible,ImGuiWindowFlags_AlwaysAutoResize|ImGuiWindowFlags_NoSavedSettings)) {
                for(const auto& match:m_completions)if(ImGui::Selectable(match.c_str())) {
                    m_code.Complete(match);m_scriptDirty=m_code.GetText()!=m_sourceSaved;m_completionVisible=false;
                }
            }
            ImGui::End();
        }
        ImGui::TextColored(Design::Muted,"%s %d, %s %d",Tr("Ln"),m_code.CursorLine(),Tr("Col"),m_code.CursorColumn());
        ImGui::SameLine();ImGui::TextColored(Design::Muted,"  /  UTF-8  /  %s",cpp?"C++":"ConcordScript");
        const char* state=readOnly?Tr("Read only"):m_scriptDirty?Tr("Unsaved changes"):Tr("Saved");
        ImGui::SameLine(std::max(ImGui::GetCursorPosX(),ImGui::GetWindowContentRegionMax().x-ImGui::CalcTextSize(state).x));
        ImGui::TextColored(m_scriptDirty?ImVec4{0.95f,0.78f,0.45f,1.0f}:Design::Muted,"%s",state);
    }
    ImGui::End();
}

void Workspace::NavigateDiagnostic(const std::string& line)
{
    static const std::regex diagnostic(R"(((?:[A-Za-z]:[\\/]|\\\\)[^\r\n]*?\.cx|[^\s:"'()]+\.cx)["']?[:(]([0-9]+))",std::regex::icase);
    std::smatch match;
    if(!std::regex_search(line,match,diagnostic))return;
    std::string name=match[1].str();
    const auto drive=name.find(":\\");const auto slashDrive=name.find(":/");
    const auto start=drive!=std::string::npos?drive:slashDrive;
    if(start!=std::string::npos && start>0)name=name.substr(start-1);
    while(!name.empty() && (std::isspace(static_cast<unsigned char>(name.front())) || name.front()=='\'' || name.front()=='"'))name.erase(name.begin());
    while(!name.empty() && (name.back()=='\'' || name.back()=='"'))name.pop_back();
    auto candidate=Utf8Path(name);
    if(candidate.is_absolute() && !IsProjectFile(m_project,candidate))throw std::runtime_error(Tr("This diagnostic refers to a source outside the project."));
    if(!candidate.is_absolute())candidate=m_project/candidate;
    if(!IsProjectFile(m_project,candidate) || !std::filesystem::is_regular_file(candidate)) {
        RefreshScriptFiles(true);
        const auto leaf=Utf8Path(name).filename();
        auto found=m_scriptFiles.end();
        for(auto it=m_scriptFiles.begin();it!=m_scriptFiles.end();++it) {
            if(it->filename()==leaf || line.find(Utf8Text(it->filename()))!=std::string::npos) {
                if(found!=m_scriptFiles.end())throw std::runtime_error(Tr("The diagnostic file name is ambiguous; open the source from the Project panel."));
                found=it;
            }
        }
        if(found==m_scriptFiles.end())throw std::runtime_error(Tr("This diagnostic does not refer to a source file inside the project."));
        candidate=*found;
    }
    const auto number=std::stoll(match[2].str());
    if(number<=0 || number>std::numeric_limits<int>::max())throw std::runtime_error("Diagnostic line number is invalid.");
    OpenScript(candidate);m_code.SetError(static_cast<int>(number),line);m_code.GoToLine(static_cast<int>(number));
    SwitchPage(2);m_focusSource=true;ImGui::SetWindowFocus("###ConcordScript");
}

void Workspace::Console()
{
    if(ImGui::Begin(TrId("Build output").c_str())) {
        const bool busy=m_process.Busy();
        if(busy){Design::Spinner(ImGui::GetFontSize()*0.45f,ImGui::GetColorU32(Design::Accent));ImGui::SameLine();}
        ImGui::AlignTextToFramePadding();
        ImGui::TextColored(Design::Muted,"%s",busy?Tr("BUILD / RUN ACTIVE"):Tr("OUTPUT"));ImGui::SameLine();
        if(Design::Ghost("Clear output","delete")){m_consoleHiddenPrefix=m_process.Output();m_consoleRaw.clear();m_consoleLines.clear();}
        ImGui::SameLine();if(Design::Ghost("Copy output","copy"))ImGui::SetClipboardText(m_process.Output().c_str());
        ImGui::SameLine();ImGui::Checkbox(Tr("Follow"),&m_outputFollow);
        ImGui::SameLine();ImGui::Checkbox(Tr("Errors / warnings"),&m_outputErrorsOnly);
        ImGui::SameLine();ImGui::SetNextItemWidth(-FLT_MIN);ImGui::InputTextWithHint("##filterOutput",Tr("Filter output..."),m_outputFilter,sizeof(m_outputFilter));
        auto output=m_process.Output();
        if(!m_consoleHiddenPrefix.empty()) {
            if(output.starts_with(m_consoleHiddenPrefix))output.erase(0,m_consoleHiddenPrefix.size());else m_consoleHiddenPrefix.clear();
        }
        const bool changed=output!=m_consoleRaw;
        if(changed) {
            m_consoleRaw=output;m_consoleLines.clear();std::istringstream input(output);std::string line;
            while(std::getline(input,line)){if(!line.empty() && line.back()=='\r')line.pop_back();m_consoleLines.push_back(std::move(line));}
        }
        std::vector<size_t> visible;
        for(size_t i=0;i<m_consoleLines.size();++i)if((!m_outputErrorsOnly || HasDiagnostic(m_consoleLines[i])) && ContainsText(m_consoleLines[i],m_outputFilter))visible.push_back(i);
        ImGui::PushStyleColor(ImGuiCol_ChildBg,ImVec4{0.047f,0.047f,0.052f,1.0f});
        ImGui::BeginChild("OutputLines",{},ImGuiChildFlags_Borders,ImGuiWindowFlags_HorizontalScrollbar);
        auto& fonts=ImGui::GetIO().Fonts->Fonts;
        if(fonts.Size>1)ImGui::PushFont(fonts[1]);
        if(visible.empty())ImGui::TextColored(Design::Muted,"%s",m_consoleRaw.empty()?Tr("Build or run the project to see output here."):Tr("No matching output."));
        ImGuiListClipper clipper;clipper.Begin(static_cast<int>(visible.size()));
        while(clipper.Step())for(int row=clipper.DisplayStart;row<clipper.DisplayEnd;++row) {
            const auto index=visible[row];const auto& line=m_consoleLines[index];ImGui::PushID(static_cast<int>(index));
            const bool diagnostic=FoldCase(line).find(".cx")!=std::string::npos;
            if(HasDiagnostic(line))ImGui::PushStyleColor(ImGuiCol_Text,ImVec4{0.97f,0.64f,0.43f,1});
            if(diagnostic) {
                if(ImGui::Selectable(line.c_str(),false,ImGuiSelectableFlags_None,{std::max(ImGui::GetContentRegionAvail().x,ImGui::CalcTextSize(line.c_str()).x),0}))
                    Attempt([&]{NavigateDiagnostic(line);});
                if(ImGui::IsItemHovered(ImGuiHoveredFlags_ForTooltip))ImGui::SetTooltip("%s",Tr("Open this diagnostic in the code editor"));
            } else ImGui::TextUnformatted(line.c_str());
            if(HasDiagnostic(line))ImGui::PopStyleColor();
            ImGui::PopID();
        }
        if(fonts.Size>1)ImGui::PopFont();
        if(changed && m_outputFollow)ImGui::SetScrollHereY(1.0f);
        ImGui::EndChild();
        ImGui::PopStyleColor();
    }
    ImGui::End();
}
}
