// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
#include "editor/Localization.h"
#include <windows.h>
#include <string_view>
#include <unordered_map>
#include <utility>

namespace Concord::Editor {
namespace {
/** English source text and its Simplified Chinese interface translation. */
constexpr std::pair<const char*,const char*> Chinese[]={
    {" (hidden)","（已隐藏）"},
    {"%.0f%%  |  Drag to move, corner to resize  |  Shift toggles snapping","%.0f%%  |  拖动移动，拖拽右下角调整大小  |  按住 Shift 切换吸附"},
    {"%zu elements","%zu 个元素"},
    {".yu path inside the current project","当前项目中的 .yu 路径"},
    {"0 = unlimited","0 = 不限制"},
    {"3D","3D"},
    {"3D scene","3D 场景"},
    {"3D scene  /  Code  /  User interface","3D 场景  /  代码  /  用户界面"},
    {"3D starter scene","3D 入门场景"},
    {"A file with this name already exists. Existing source is never overwritten.","已存在同名文件。编辑器不会覆盖现有源码。"},
    {"A folder with this name already exists in that location.","该位置已存在同名文件夹。"},
    {"A lit stage with a physics floor and three material samples.","带光照的舞台，包含物理地面和三种材质示例。"},
    {"A scene supports at most 10000 objects.","一个场景最多支持 10000 个对象。"},
    {"About","关于"},
    {"About Concord Flash","关于 Concord Flash"},
    {"Add","添加"},
    {"Add object","添加对象"},
    {"Added","已添加"},
    {"Advanced toolchain settings","高级工具链设置"},
    {"All changes saved","所有更改已保存"},
    {"Altitude","高度"},
    {"Ambient color","环境光颜色"},
    {"Ambient gain","环境增益"},
    {"Ambient intensity","环境光强度"},
    {"Ambient scattering","环境散射"},
    {"Anchor (0 = start, 1 = end)","锚点（0 = 起始，1 = 末端）"},
    {"Anisotropy","各向异性"},
    {"Appearance","外观"},
    {"Apply","应用"},
    {"Audio","音频"},
    {"Automatic","自动"},
    {"Automatic (published release)","自动（使用已发布版本）"},
    {"Azimuth","方位角"},
    {"Back","后视图"},
    {"Background","背景色"},
    {"Base color","基础颜色"},
    {"Base height","基准高度"},
    {"Bloom intensity","泛光强度"},
    {"Bloom radius","泛光半径"},
    {"Bloom threshold","泛光阈值"},
    {"Blue night","蓝夜"},
    {"Bottom","底视图"},
    {"Bottom right","右下"},
    {"Bounciness","弹性"},
    {"Box","盒体"},
    {"Browse...","浏览..."},
    {"Build","构建"},
    {"BUILD / RUN ACTIVE","构建 / 运行中"},
    {"Build and play","构建并运行"},
    {"Build and play (F5)","构建并运行 (F5)"},
    {"Build and Play call the Concord CLI, which compiles ConcordScript against an engine SDK.","构建和运行会调用 Concord CLI，它基于引擎 SDK 编译 ConcordScript。"},
    {"Build and Play use these paths. An empty SDK path lets the CLI download the published release.","构建和运行使用以下路径。SDK 留空时，CLI 会自动下载已发布版本。"},
    {"Build or run the project to see output here.","构建或运行项目后，输出会显示在这里。"},
    {"Build output","构建输出"},
    {"Build project","构建项目"},
    {"Build project (Ctrl+B)","构建项目 (Ctrl+B)"},
    {"Building and launching the game...","正在构建并启动游戏..."},
    {"Building the project...","正在构建项目..."},
    {"Button","按钮"},
    {"Camera views","相机视角"},
    {"Cancel","取消"},
    {"Cannot finish writing the new script.","无法完成新脚本的写入。"},
    {"Canvas tools","画布工具"},
    {"Cast shadows","投射阴影"},
    {"Center","居中"},
    {"Checkbox","复选框"},
    {"Choose a location for the new project.","请为新项目选择位置。"},
    {"Choose a scene inside the current project.","请选择当前项目中的场景。"},
    {"Choose a template, a name and a location. The editor sets everything up for you.","选择模板、名称和位置，编辑器会为你完成所有配置。"},
    {"Choose a UI document inside the current project.","请选择当前项目中的 UI 文档。"},
    {"Choose the Concord SDK folder","选择 Concord SDK 文件夹"},
    {"Choose the parent folder for your project","选择项目所在的父文件夹"},
    {"Chromatic aberration","色差"},
    {"Clear color","清屏颜色"},
    {"Clear output","清空输出"},
    {"Click to open in its workspace","点击在对应工作区中打开"},
    {"Clipboard and edit actions","剪贴板与编辑操作"},
    {"Close","关闭"},
    {"Close search","关闭搜索"},
    {"Close window","关闭窗口"},
    {"Close workspace","关闭工作区"},
    {"Cloud type","云类型"},
    {"Clouds, fog and post processing are saved and exported to the game; the editor preview uses the raster path.","云、雾和后期处理会保存并导出到游戏中；编辑器预览使用光栅化渲染路径。"},
    {"Coarse steps","粗略步进"},
    {"Code","代码"},
    {"Col","列"},
    {"Color","颜色"},
    {"Color and post processing","色彩与后期处理"},
    {"Complete word","补全单词"},
    {"Completions","补全"},
    {"Concord CLI (concord.exe) was not found.","未找到 Concord CLI（concord.exe）。"},
    {"Concord CLI (concord.exe) was not found. Choose it to build and play.","未找到 Concord CLI（concord.exe），请先选择它再构建和运行。"},
    {"Concord CLI (concord.exe) was not found. Choose it under Advanced toolchain settings.","未找到 Concord CLI（concord.exe），请在“高级工具链设置”中选择。"},
    {"Concord on GitHub","GitHub 上的 Concord"},
    {"concord.exe builds, runs and creates projects.","concord.exe 负责构建、运行和创建项目。"},
    {"ConcordScript (.cx)","ConcordScript 脚本 (.cx)"},
    {"Content","内容"},
    {"Contrast","对比度"},
    {"Control type","控件类型"},
    {"Coordinates use reference pixels. Runtime layout scales uniformly to the host window; anchors follow the parent panel.","坐标使用参考像素。运行时布局会按宿主窗口等比缩放；锚点相对于父面板。"},
    {"Copied","已复制"},
    {"copy","副本"},
    {"Copy","复制"},
    {"Copy / paste / duplicate","复制 / 粘贴 / 创建副本"},
    {"Copy log","复制日志"},
    {"Copy output","复制输出"},
    {"Copy path","复制路径"},
    {"Copy selection (Ctrl+C)","复制选中内容 (Ctrl+C)"},
    {"Corner radius","圆角半径"},
    {"Coverage","覆盖率"},
    {"Create","新建"},
    {"Create a new project","创建新项目"},
    {"Create a new scene","创建新场景"},
    {"Create a project or import a folder to begin.","新建项目或导入文件夹即可开始。"},
    {"Create interface","创建界面"},
    {"Create or open a .yu file to design an interface.","新建或打开 .yu 文件来设计界面。"},
    {"Create project","创建项目"},
    {"Create reusable panels, controls and window buttons. The canvas uses Concord's runtime UI renderer.","创建可复用的面板、控件和窗口按钮。画布使用 Concord 运行时 UI 渲染器。"},
    {"Create script","创建脚本"},
    {"Created","已创建"},
    {"Creates","将创建"},
    {"Creates a ConcordScript class in the project folder.","在项目文件夹中创建一个 ConcordScript 类。"},
    {"Creating project...","正在创建项目..."},
    {"Cube","立方体"},
    {"Custom event only","仅触发自定义事件"},
    {"Cut","剪切"},
    {"Delete","删除"},
    {"Delete element and children","删除元素及其子元素"},
    {"Delete object","删除对象"},
    {"Delete subtree","删除子树"},
    {"Deleted","已删除"},
    {"Density","密度"},
    {"Design your interface","设计你的界面"},
    {"Detail scale","细节尺度"},
    {"Detail strength","细节强度"},
    {"Development SDK","开发版 SDK"},
    {"Dimensions","尺寸"},
    {"DOCUMENT","文档"},
    {"Document canvas","文档画布"},
    {"Done","完成"},
    {"Don't save","不保存"},
    {"Drift speed","漂移速度"},
    {"Duplicate","创建副本"},
    {"Duplicate subtree","复制子树"},
    {"Duplicate UI element","复制 UI 元素"},
    {"Dynamic body","动态刚体"},
    {"Dynamic physics box","动态物理盒"},
    {"Each project opens in its own editor window.","每个项目都会在独立的编辑器窗口中打开。"},
    {"Edit","编辑"},
    {"Edit objects in the 3D workspace.","请在 3D 工作区中编辑对象。"},
    {"ELEMENT","元素"},
    {"Elevation","高度角"},
    {"Emission","自发光"},
    {"Empty scene","空场景"},
    {"Enable project entry point","启用项目入口"},
    {"Enabled","启用"},
    {"Engine SDK","引擎 SDK"},
    {"Enter a valid project folder name.","请输入有效的项目文件夹名称。"},
    {"Entry point","入口"},
    {"ENVIRONMENT","环境"},
    {"Errors / warnings","仅错误 / 警告"},
    {"Example: PlayerController.cx","示例：PlayerController.cx"},
    {"Exit","退出"},
    {"Exit full screen (F11)","退出全屏 (F11)"},
    {"Exposure","曝光"},
    {"Far plane","远裁剪面"},
    {"Field of view","视野"},
    {"File","文件"},
    {"File name","文件名"},
    {"File name inside the current project","当前项目中的文件名"},
    {"Filter output...","筛选输出..."},
    {"Find","查找"},
    {"Find / find next","查找 / 查找下一个"},
    {"Find in this file...","在此文件中查找..."},
    {"Fit UI canvas","适应画布"},
    {"Fly through the scene","在场景中飞行"},
    {"Focus","聚焦"},
    {"Focus selection","聚焦选中对象"},
    {"Focus selection / frame all","聚焦选中 / 显示全部"},
    {"Fog density","雾密度"},
    {"Fog steps","雾步进次数"},
    {"Folder not available","文件夹不可用"},
    {"Follow","自动滚动"},
    {"Follow Windows","跟随系统"},
    {"Font scale","字体缩放"},
    {"Found","已找到"},
    {"Frame all objects","显示全部对象"},
    {"Frame all objects (Home)","显示全部对象 (Home)"},
    {"Frame limit","帧率上限"},
    {"Friction","摩擦力"},
    {"Front","前视图"},
    {"Full screen","全屏"},
    {"Full screen (F11)","全屏 (F11)"},
    {"Game camera","游戏相机"},
    {"Game camera gizmo","游戏相机辅助线"},
    {"Game title","游戏标题"},
    {"Game window","游戏窗口"},
    {"General","常规"},
    {"GENERATED / READ ONLY","自动生成 / 只读"},
    {"Generated from project settings. Read only.","由项目设置生成，只读。"},
    {"Go","跳转"},
    {"Go to line","跳转到行"},
    {"Graphite","石墨"},
    {"Gray","灰色"},
    {"Grid","网格"},
    {"Grid spacing","网格间距"},
    {"Ground","地面"},
    {"Height falloff","高度衰减"},
    {"Help","帮助"},
    {"Hide","隐藏"},
    {"Hide object","隐藏对象"},
    {"Hide output","隐藏输出"},
    {"Hierarchy","层级"},
    {"Horizon","地平线"},
    {"Import","导入"},
    {"Initial input value","初始输入值"},
    {"Initial scene","初始场景"},
    {"Initial scene saved","初始场景已保存"},
    {"Initial value","初始值"},
    {"Initially checked","默认勾选"},
    {"Inspector","检查器"},
    {"Intensity","强度"},
    {"Interface","界面"},
    {"Interface scale","界面缩放"},
    {"Keyboard shortcuts","键盘快捷键"},
    {"Label","文本标签"},
    {"Language","语言"},
    {"Last operation completed","上次操作已完成"},
    {"Last operation failed","上次操作失败"},
    {"Layout","布局"},
    {"Leave empty to let the CLI download the published release.","留空则由 CLI 自动下载已发布版本。"},
    {"Left","左视图"},
    {"License","许可证"},
    {"Light gain","光照增益"},
    {"Light steps","光照步进"},
    {"Line","行"},
    {"Ln","行"},
    {"Local","局部"},
    {"Local space: axes follow the object","局部空间：坐标轴跟随对象"},
    {"Location","位置"},
    {"Lock rotation","锁定旋转"},
    {"Look at","注视点"},
    {"March steps","步进次数"},
    {"Mass (kg)","质量 (kg)"},
    {"Material","材质"},
    {"Maximize","最大化"},
    {"Maximize / restore","最大化 / 还原"},
    {"Metallic","金属度"},
    {"Minimize","最小化"},
    {"Minimize window","最小化窗口"},
    {"Moon direction","月光方向"},
    {"Moon intensity","月光强度"},
    {"Move","移动"},
    {"Move (W)","移动 (W)"},
    {"Move / rotate / scale","移动 / 旋转 / 缩放"},
    {"Move game camera here","将游戏相机移到此视角"},
    {"Near plane","近裁剪面"},
    {"New ConcordScript","新建 ConcordScript"},
    {"New project","新建项目"},
    {"New scene","新建场景"},
    {"New scene...","新建场景..."},
    {"New UI document","新建 UI 文档"},
    {"New UI document...","新建 UI 文档..."},
    {"Next","下一个"},
    {"No match in this file.","此文件中没有匹配项。"},
    {"No matching files","没有匹配的文件"},
    {"No matching output.","没有匹配的输出。"},
    {"No matching projects","没有匹配的项目"},
    {"None","无"},
    {"Not found","未找到"},
    {"Nothing selected","未选择对象"},
    {"Object","对象"},
    {"objects","个对象"},
    {"On click","点击时"},
    {"Only a camera and sunlight, ready for your own ideas.","只有相机和太阳光，随你发挥创意。"},
    {"Open","打开"},
    {"Open .yu document","打开 .yu 文档"},
    {"Open a Concord project folder","打开 Concord 项目文件夹"},
    {"Open a valid project before creating a script.","请先打开有效的项目再创建脚本。"},
    {"Open interface","打开界面"},
    {"Open scene","打开场景"},
    {"Open scene...","打开场景..."},
    {"Open this diagnostic in the code editor","在代码编辑器中打开此诊断"},
    {"Open UI document","打开 UI 文档"},
    {"Open UI document...","打开 UI 文档..."},
    {"Opened","已打开"},
    {"Orbit the view","旋转视角"},
    {"Orthographic","正交"},
    {"Orthographic size","正交尺寸"},
    {"OUTPUT","输出"},
    {"Pan the view","平移视角"},
    {"Panel","面板"},
    {"Parent panel","父面板"},
    {"Paste","粘贴"},
    {"Pasted","已粘贴"},
    {"Perspective","透视"},
    {"Physics","物理"},
    {"Physics runs in the game started by Play.","物理模拟在点击“运行”启动的游戏中进行。"},
    {"Placeholder","占位文本"},
    {"Plane","平面"},
    {"Platform","平台"},
    {"Play","运行"},
    {"Play starts the game with these settings.","点击运行时，游戏将使用以下设置启动。"},
    {"Play uses the initial scene, UI and window settings above.","运行时使用上方的初始场景、界面和窗口设置。"},
    {"Position","位置"},
    {"Preferences","首选项"},
    {"Preferences...","首选项..."},
    {"Presets","预设"},
    {"Process completed successfully","进程已成功完成"},
    {"Process failed; see Build output","进程失败，请查看构建输出"},
    {"Progress","进度条"},
    {"Project","项目"},
    {"Project actions","项目操作"},
    {"Project Manager","项目管理器"},
    {"Project manager...","项目管理器..."},
    {"Project name","项目名称"},
    {"Project opened. Ctrl+S saves everything, F5 builds and plays.","项目已打开。Ctrl+S 保存全部，F5 构建并运行。"},
    {"Project settings","项目设置"},
    {"Project settings...","项目设置..."},
    {"Project startup enabled. The previous Main.cx was backed up in .editor.","已启用项目入口。原 Main.cx 已备份到 .editor 文件夹。"},
    {"Project startup settings saved","项目启动设置已保存"},
    {"Projection","投影方式"},
    {"Projects","项目"},
    {"Read only","只读"},
    {"Ready","就绪"},
    {"Recent projects","最近的项目"},
    {"Redo","重做"},
    {"Redo (Ctrl+Y)","重做 (Ctrl+Y)"},
    {"Redo UI edit","重做 UI 编辑"},
    {"Reference resolution","参考分辨率"},
    {"Refresh","刷新"},
    {"Relative to the project folder, ending in .scene","相对于项目文件夹，以 .scene 结尾"},
    {"Remove from list","从列表中移除"},
    {"Rename","重命名"},
    {"Rename / delete","重命名 / 删除"},
    {"Rename ID","重命名 ID"},
    {"Rename UI element","重命名 UI 元素"},
    {"Renderer","渲染器"},
    {"Rendering","渲染"},
    {"Replace file","替换文件"},
    {"Reset","重置"},
    {"Reset transform","重置变换"},
    {"Resizable","可调整大小"},
    {"Resolution","分辨率"},
    {"Restore default layout","恢复默认布局"},
    {"Restore down","向下还原"},
    {"Right","右视图"},
    {"RMB orbit   MMB pan   Wheel zoom","右键 旋转   中键 平移   滚轮 缩放"},
    {"RMB orbit   RMB+WASD fly   MMB pan   Wheel zoom   F focus   W/E/R tools","右键 旋转   右键+WASD 飞行   中键 平移   滚轮 缩放   F 聚焦   W/E/R 工具"},
    {"Rotate","旋转"},
    {"Rotate (E)","旋转 (E)"},
    {"Rotation","旋转"},
    {"Roughness","粗糙度"},
    {"Running...","运行中..."},
    {"Saturation","饱和度"},
    {"Save","保存"},
    {"Save all","全部保存"},
    {"Save all (Ctrl+S)","全部保存 (Ctrl+S)"},
    {"Save and close","保存并关闭"},
    {"Save and continue","保存并继续"},
    {"Save as...","另存为..."},
    {"Save changes to the current scene?","是否保存对当前场景的更改？"},
    {"Save interface","保存界面"},
    {"Save scene as","场景另存为"},
    {"Save scene as...","场景另存为..."},
    {"Save source (Ctrl+S)","保存源码 (Ctrl+S)"},
    {"Save the current interface before switching?","切换前是否保存当前界面？"},
    {"Save the current scene as a new file","将当前场景另存为新文件"},
    {"Save the interface in the UI workspace, then retry this action.","请先在 UI 工作区保存界面，然后重试。"},
    {"Save the new interface, then close the workspace again.","请先保存新界面，然后再次关闭工作区。"},
    {"Save UI document","保存 UI 文档"},
    {"Save your changes before closing?","关闭前是否保存更改？"},
    {"Saved","已保存"},
    {"Saved scripts, scene, interface and project settings","已保存脚本、场景、界面和项目设置"},
    {"Scale","缩放"},
    {"Scale (R)","缩放 (R)"},
    {"Scene","场景"},
    {"Scene (.scene)","场景 (.scene)"},
    {"Scene grid","场景网格"},
    {"SCENE OBJECTS","场景对象"},
    {"Search files...","搜索文件..."},
    {"Search objects...","搜索对象..."},
    {"Search projects by name or folder...","按名称或文件夹搜索项目..."},
    {"Select a CLI project containing Main.cx","请选择包含 Main.cx 的项目"},
    {"Select a panel before adding a child. Parent and anchors are editable in Properties.","添加子元素前请先选择一个面板。父级和锚点可在属性面板中修改。"},
    {"Select an interface file to edit its properties.","请选择界面文件以编辑其属性。"},
    {"Select an object in the hierarchy or viewport.","在层级面板或视口中选择一个对象。"},
    {"Set as initial scene","设为初始场景"},
    {"Set as startup UI","设为启动界面"},
    {"Shape","形状"},
    {"Show","显示"},
    {"Show game camera and sun","显示游戏相机和太阳光"},
    {"Show grid","显示网格"},
    {"Show in Explorer","在资源管理器中显示"},
    {"Show object","显示对象"},
    {"Show output","显示输出"},
    {"Show project folder","打开项目文件夹"},
    {"Show UI grid","显示 UI 网格"},
    {"Size","大小"},
    {"Sky and ambient","天空与环境光"},
    {"Slider","滑块"},
    {"Snap","吸附"},
    {"Snap steps","吸附步长"},
    {"Snap to grid","吸附到网格"},
    {"Snap to steps","按步长吸附"},
    {"Source changed outside the editor; recover your edits before reloading.","源码已在编辑器外被修改，请先找回你的编辑再重新加载。"},
    {"Source saved","源码已保存"},
    {"Stable element ID","稳定元素 ID"},
    {"Start in full screen","以全屏启动"},
    {"Start with a letter or underscore; use a ConcordScript identifier.","请以字母或下划线开头，使用合法的 ConcordScript 标识符。"},
    {"Startup","启动"},
    {"Startup UI","启动界面"},
    {"Startup UI saved","启动界面已保存"},
    {"Static body","静态刚体"},
    {"Static physics box","静态物理盒"},
    {"Step distance","步进距离"},
    {"Stop","停止"},
    {"Stop (Shift+F5)","停止 (Shift+F5)"},
    {"Style","样式"},
    {"Sun light","太阳光"},
    {"Sun multiplier","太阳光倍率"},
    {"Sun scattering","太阳散射"},
    {"Switch workspace","切换工作区"},
    {"System title bar","系统标题栏"},
    {"Text","文本"},
    {"Text / foreground","文本 / 前景色"},
    {"Text input","文本输入框"},
    {"That file already exists; choose another name.","该文件已存在，请换一个名称。"},
    {"The diagnostic file name is ambiguous; open the source from the Project panel.","诊断信息中的文件名不唯一，请从项目面板中打开源码。"},
    {"The file does not exist.","文件不存在。"},
    {"The running build or game will also stop.","正在运行的构建或游戏也会被停止。"},
    {"The scene changed outside the editor. Use File > Save scene as... to keep both versions.","场景已在编辑器外被修改。请使用“文件 > 场景另存为...”保留两个版本。"},
    {"Theme","主题"},
    {"Thickness","厚度"},
    {"Thin plane","薄平面"},
    {"This diagnostic does not refer to a source file inside the project.","此诊断信息未指向项目中的源文件。"},
    {"This diagnostic refers to a source outside the project.","此诊断信息指向项目外的源文件。"},
    {"This file exists. Replace its contents?","该文件已存在，是否替换其内容？"},
    {"This file is not inside a Concord project (no Main.cx in its parent folders).","该文件不在 Concord 项目中（上级文件夹里没有 Main.cx）。"},
    {"This name is reserved by Windows.","该名称被 Windows 保留。"},
    {"This name is used by a generated file; choose another name.","该名称已被自动生成的文件使用，请换一个名称。"},
    {"This project has a custom Main.cx. Enable the project entry point to make Play use these settings. The old Main.cx is backed up in .editor.","此项目使用自定义的 Main.cx。启用项目入口后，运行将使用这些设置；原 Main.cx 会备份到 .editor 文件夹。"},
    {"This scene is empty.","此场景为空。"},
    {"Toggle full screen","切换全屏"},
    {"Toolchain","工具链"},
    {"Toolchain...","工具链..."},
    {"Top","顶视图"},
    {"Top left","左上"},
    {"Transform","变换"},
    {"Try a different name or folder.","请尝试其他名称或文件夹。"},
    {"Type","类型"},
    {"UI Canvas","UI 画布"},
    {"UI document (.yu)","UI 文档 (.yu)"},
    {"UI Elements","UI 元素"},
    {"UI Properties","UI 属性"},
    {"Undo","撤销"},
    {"Undo (Ctrl+Z)","撤销 (Ctrl+Z)"},
    {"Undo / redo","撤销 / 重做"},
    {"Undo UI edit","撤销 UI 编辑"},
    {"Unsaved changes","有未保存的更改"},
    {"Unsaved edits to scripts, the scene or the interface will be lost if you close without saving.","如果不保存就关闭，对脚本、场景或界面的未保存修改将会丢失。"},
    {"Unsaved interface","未保存的界面"},
    {"Unsaved scene","未保存的场景"},
    {"Use current 3D view","使用当前 3D 视角"},
    {"Use letters, numbers and underscores. Folder paths are not allowed.","只能使用字母、数字和下划线，不能包含文件夹路径。"},
    {"Use the .scene extension for new scenes.","新场景请使用 .scene 扩展名。"},
    {"User interface","用户界面"},
    {"Version","版本"},
    {"View","视图"},
    {"Vignette","暗角"},
    {"Visible","可见"},
    {"Visible in game","在游戏中可见"},
    {"Volumetric clouds","体积云"},
    {"Volumetric fog","体积雾"},
    {"VSync","垂直同步"},
    {"Wall","墙体"},
    {"Weather scale","天气尺度"},
    {"Window actions execute in the game. The designer preview is always non-interactive.","窗口操作在游戏中执行；设计器预览始终不响应交互。"},
    {"World","世界"},
    {"World space: axes follow the scene","世界空间：坐标轴跟随场景"},
    {"Your next world starts here","你的下一个世界从这里开始"},
    {"Zenith","天顶"},
    {"Zoom","缩放"},
};
LanguagePreference preference=LanguagePreference::System;
bool chinese=false;

const std::unordered_map<std::string_view,const char*>& Table()
{
    static const auto table=[] {
        std::unordered_map<std::string_view,const char*> result;
        result.reserve(std::size(Chinese));
        for(const auto& [english,translated]:Chinese)result.emplace(english,translated);
        return result;
    }();
    return table;
}
bool SystemPrefersChinese()
{
    return PRIMARYLANGID(GetUserDefaultUILanguage())==LANG_CHINESE;
}
}

void SetLanguage(LanguagePreference value)
{
    preference=value;
    chinese=value==LanguagePreference::Chinese || (value==LanguagePreference::System && SystemPrefersChinese());
}
LanguagePreference CurrentLanguagePreference() {return preference;}
bool IsChinese() {return chinese;}
const char* Tr(const char* english)
{
    if(!chinese || !english)return english;
    const auto found=Table().find(english);
    return found==Table().end()?english:found->second;
}
std::string TrId(const char* english,const char* id)
{
    return std::string(Tr(english))+"###"+(id?id:english);
}
const char* TranslationGlyphs()
{
    static const std::string glyphs=[] {
        std::string text;
        for(const auto& entry:Chinese)text+=entry.second;
        text+="简体中文跟随系统（）“”：，。、";
        return text;
    }();
    return glyphs.c_str();
}
}
