// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
#include "editor/ProjectRuntime.h"
#include "editor/SceneDocument.h"
#include <Concord/CUiDocument.h>
#include <algorithm>
#include <iomanip>
#include <sstream>

namespace Concord::Editor {
bool IsProjectEntryScript(const std::string& source)
{
    auto normalized=source;std::erase(normalized,'\r');
    return normalized==ProjectEntryScript();
}
PreparedProjectRuntime PrepareProjectRuntime(const std::filesystem::path& root,const ProjectDocument& project)
{
    project.ValidatePaths(root,true);
    SceneDocument scene;scene.Parse(ReadText(ResolveProjectPath(root,project.startupScene,true)));
    std::string uiText;
    if(!project.startupUi.empty()) {
        UiDocument ui;ui.Load(ResolveProjectPath(root,project.startupUi,true));uiText=ui.Serialize();
    }
    return {scene.ExportScript(),ExportProjectRuntime(project,uiText,scene.UsesPhysics())};
}
void SaveProjectRuntime(const std::filesystem::path& root,const PreparedProjectRuntime& prepared)
{
    const auto scene=ResolveProjectPath(root,"SceneLayout.cx"),runtime=ResolveProjectPath(root,"ProjectRuntime.cx");
    for(const auto& file:{scene,runtime}) {
        if(std::filesystem::exists(file) && !ReadText(file).starts_with("// Generated by Concord Editor."))
            throw std::runtime_error("Generated file would replace user code: "+file.filename().string());
    }
    if(!std::filesystem::exists(scene) || ReadText(scene)!=prepared.sceneSource)WriteText(scene,prepared.sceneSource);
    if(!std::filesystem::exists(runtime) || ReadText(runtime)!=prepared.runtimeSource)WriteText(runtime,prepared.runtimeSource);
}
std::string ProjectEntryScript()
{
    return "// Concord Editor project entry. Startup settings are stored in Concord.project.\n"
           "use Concord.CApplication;\nuse Project.ProjectRuntime;\n\n@entry {\n"
           "    ProjectRuntime::Runtime runtime;\n"
           "    Concord::Game game(ProjectRuntime::Runtime::Config());\n"
           "    runtime.Attach(game);\n    game.Run();\n"
           "    game.OnUi({});\n    game.OnUpdate({});\n    game.DetachWindow();\n    return 0;\n};\n";
}
std::string ExportProjectRuntime(const ProjectDocument& project,const std::string& uiDocument,bool physics)
{
    project.Validate();
    std::string delimiter="CFYU";
    while(uiDocument.find(")"+delimiter+"\"")!=std::string::npos)delimiter+='X';
    if(delimiter.size()>16)throw std::runtime_error("UI text cannot be embedded in generated source");
    std::ostringstream out;
    out<<"// Generated by Concord Editor. Edit Concord.project, .scene and .yu files.\n"
         "use Concord.CApplication;\nuse Concord.CScene;\nuse Concord.CUiToolkit;\nuse Concord.CUiDocument;\n"
         "use Concord.CPhysics;\nuse Project.SceneLayout;\n@include(path=\"cstdlib\", system=true);\n\n"
         "class Runtime {\npublic:\n    Concord::Scene scene;\n    Concord::UiDocument ui;\n"
         "    Concord::Window window{ {.title="<<std::quoted(project.name)<<",.resolution={"<<project.width<<','<<project.height
       <<"},.mode=Concord::WindowMode::"<<(project.fullscreen?"Fullscreen":"Windowed")
       <<",.resizable="<<(project.resizable?"true":"false")
       <<",.visible=!std::getenv(\"CONCORD_EDITOR_GAME_SMOKE\")"
       <<",.vsync="<<(project.vsync?"true":"false")
       <<",.decorated="<<(project.decorated?"true":"false")<<"} };\n"
         "    static Concord::GameConfig Config() {\n"
         "        return {.enableRayTracing=false,.frameRateLimit="<<project.targetFps<<",.enableUiToolkit=true};\n    }\n"
         "    void Attach(Concord::Game& game) {\n"
         "        game.AttachWindow(window);\n        SceneLayout::Layout::Build(scene);\n";
    if(physics)out<<"        game.Systems().Add<Concord::PhysicsSystem>();\n";
    out<<"        game.LoadScene(scene);\n";
    if(!uiDocument.empty())out<<"        ui.Parse(R\""<<delimiter<<'('<<uiDocument<<')'<<delimiter<<"\");\n";
    out<<R"(        game.OnUi([this,&game] {
            if (std::getenv("CONCORD_EDITOR_GAME_SMOKE") && game.FrameCount()>60) {game.Quit();return;}
            auto* toolkit=game.Toolkit();
            if (!toolkit) return;
            auto* viewport=ImGui::GetMainViewport();
            ImGui::SetNextWindowPos(viewport->Pos);
            ImGui::SetNextWindowSize(viewport->Size);
            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,ImVec2(0,0));
            ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding,0.0f);
            if(ImGui::Begin("Game canvas",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoSavedSettings|ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoBringToFrontOnFocus)) {
                const auto scale=ImGui::GetIO().DisplayFramebufferScale;
                toolkit->SetSceneViewport(static_cast<Concord::u32>(viewport->Size.x*scale.x),static_cast<Concord::u32>(viewport->Size.y*scale.y));
                ImGui::Image(toolkit->SceneTexture(),viewport->Size);
                (void)ui.Draw({.position={viewport->Pos.x,viewport->Pos.y},.size={viewport->Size.x,viewport->Size.y},.window=&window});
            }
            ImGui::End();ImGui::PopStyleVar(2);
        });
    }
};
)";
    return out.str();
}
}
