#include "MetadataCodeGen.h"

#include "MetadataShader.h"

#include <sstream>

namespace ConcordScript {
namespace {

void EscapeCpp(std::ostringstream& out, const std::string& value)
{
    out << '"';
    constexpr char digits[] = "0123456789abcdef";
    for (const unsigned char character : value) {
        if (character == '\\' || character == '"') {
            out << '\\' << static_cast<char>(character);
        } else if (character == '\n') {
            out << "\\n";
        } else if (character == '\r') {
            out << "\\r";
        } else if (character == '\t') {
            out << "\\t";
        } else if (character < 0x20) {
            out << "\\x" << digits[(character >> 4) & 0xf] << digits[character & 0xf]
                << "\"\"";
        } else {
            out << static_cast<char>(character);
        }
    }
    out << '"';
}
struct FlatMetadata {
    std::vector<const GeneratedAnnotation*> annotations;
    std::vector<const AnnotationArg*> arguments;
    std::vector<std::size_t> firstArguments;
};
FlatMetadata Flatten(const std::vector<MetadataModule>& modules)
{
    FlatMetadata flat;
    for (const MetadataModule& module : modules) {
        for (const GeneratedAnnotation& annotation : module.annotations) {
            flat.annotations.push_back(&annotation);
            flat.firstArguments.push_back(flat.arguments.size());
            for (const AnnotationArg& argument : annotation.parsedArguments) {
                flat.arguments.push_back(&argument);
            }
        }
    }
    return flat;
}
} // namespace

std::string RenderMetadataHeader(const std::vector<MetadataModule>& modules)
{
    const FlatMetadata flat = Flatten(modules);
    std::ostringstream out;
    out << "// Generated by concordc; do not edit.\n"
        << "#ifndef CONCORDSCRIPT_METADATA_GEN_H\n#define CONCORDSCRIPT_METADATA_GEN_H\n\n"
        << "#include <array>\n#include <cstddef>\n#include <span>\n#include <string_view>\n\n"
        << "namespace Concord::Script::Metadata {\n\n"
        << "inline constexpr std::size_t Version = 1;\n"
        << "struct ArgumentRecord { std::string_view key; std::string_view value; "
        << "std::string_view raw; bool named; bool quoted; };\n"
        << "struct AnnotationRecord { std::string_view module; std::string_view name; "
        << "std::string_view args; std::string_view body; std::string_view owner; "
        << "std::size_t line; std::size_t firstArgument; std::size_t argumentCount; };\n"
        << "struct ShaderRecord { std::string_view module; std::string_view name; "
        << "std::string_view stage; std::string_view entry; std::string_view language; "
        << "std::string_view path; bool external; std::string_view owner; std::size_t line; "
        << "std::size_t firstDefines; std::size_t defineCount; "
        << "std::size_t firstIncludeDirs; std::size_t includeDirCount; "
        << "std::size_t firstOptions; std::size_t optionCount; };\n\n";

    out << "inline constexpr std::array<ArgumentRecord, " << flat.arguments.size()
        << "> ArgumentTable{{\n";
    for (const AnnotationArg* argument : flat.arguments) {
        out << "    {";
        EscapeCpp(out, argument->key); out << ", ";
        EscapeCpp(out, argument->value); out << ", ";
        EscapeCpp(out, argument->raw); out << ", "
            << (argument->hasKey ? "true" : "false") << ", "
            << (argument->quoted ? "true" : "false") << "},\n";
    }
    out << "}};\n\n";
    out << "inline constexpr std::array<AnnotationRecord, " << flat.annotations.size()
        << "> AnnotationTable{{\n";
    std::size_t annotationIndex = 0;
    for (const MetadataModule& module : modules) {
        for (const GeneratedAnnotation& annotation : module.annotations) {
            out << "    {";
            EscapeCpp(out, module.module); out << ", ";
            EscapeCpp(out, annotation.name); out << ", ";
            EscapeCpp(out, annotation.arguments); out << ", ";
            EscapeCpp(out, annotation.body); out << ", ";
            EscapeCpp(out, annotation.owner);
            out << ", " << annotation.line << ", " << flat.firstArguments[annotationIndex]
                << ", " << annotation.parsedArguments.size() << "},\n";
            ++annotationIndex;
        }
    }
    out << "}};\n\n";
    out << RenderShaderMetadata(modules)
        << "inline constexpr std::span<const ArgumentRecord> Arguments() noexcept "
        << "{ return ArgumentTable; }\n"
        << "inline constexpr std::span<const ArgumentRecord> Arguments("
        << "const AnnotationRecord& record) noexcept\n"
        << "{ return std::span<const ArgumentRecord>(ArgumentTable).subspan("
        << "record.firstArgument, record.argumentCount); }\n"
        << "inline constexpr std::span<const AnnotationRecord> Annotations() noexcept "
        << "{ return AnnotationTable; }\n"
        << "inline const AnnotationRecord* FindAnnotation(std::string_view name) noexcept\n"
        << "{ for (const AnnotationRecord& record : AnnotationTable) "
        << "if (record.name == name) return &record; return nullptr; }\n"
        << "inline const AnnotationRecord* FindAnnotation(std::string_view module, "
        << "std::string_view name) noexcept\n"
        << "{ for (const AnnotationRecord& record : AnnotationTable) "
        << "if (record.module == module && record.name == name) return &record; "
        << "return nullptr; }\n"
        << "inline const ShaderRecord* FindShader(std::string_view name, "
        << "std::string_view stage = {}) noexcept\n"
        << "{ for (const ShaderRecord& record : ShaderTable) "
        << "if (record.name == name && (stage.empty() || record.stage == stage)) return &record; "
        << "return nullptr; }\n\n"
        << "inline const ShaderRecord* FindShader(std::string_view module, "
        << "std::string_view name, std::string_view stage) noexcept\n"
        << "{ for (const ShaderRecord& record : ShaderTable) "
        << "if (record.module == module && record.name == name && "
        << "(stage.empty() || record.stage == stage)) return &record; return nullptr; }\n\n"
        << "} // namespace Concord::Script::Metadata\n\n"
        << "#endif // CONCORDSCRIPT_METADATA_GEN_H\n";
    return out.str();
}

} // namespace ConcordScript
