#include "Registry.h"

#include <algorithm>
#include <sstream>

namespace ConcordScript {

std::string GenerateRegistryHeader()
{
    std::ostringstream out;
    out << "// Generated by concordc — do not edit.\n";
    out << "#ifndef CONCORDSCRIPT_REGISTRY_GEN_H\n";
    out << "#define CONCORDSCRIPT_REGISTRY_GEN_H\n\n";
    out << "#include <Concord/CApplication.h>\n";
    out << "#include <Concord/CScene.h>\n\n";
    out << "namespace Concord::Script {\n\n";
    out << "/** Spawns every registered component class in the project as an entity. */\n";
    out << "void RegisterAll(Concord::Scene& scene);\n";
    out << "/** Adds every `@system` class to the game's system schedule. */\n";
    out << "void AddSystems(Concord::Game& game);\n\n";
    out << "} // namespace Concord::Script\n\n";
    out << "#endif // CONCORDSCRIPT_REGISTRY_GEN_H\n";
    return out.str();
}

std::string GenerateRegistrySource(const std::vector<std::string>& registeredClasses,
                                   const std::vector<std::string>& registeredHeaderPaths,
                                   const std::vector<std::string>& systemClasses,
                                   const std::vector<std::string>& systemHeaderPaths)
{
    std::ostringstream out;
    out << "// Generated by concordc - do not edit.\n";
    out << "#include \"ConcordScriptRegistry.gen.h\"\n";
    for (const std::string& headerPath : registeredHeaderPaths) {
        out << "#include \"" << headerPath << "\"\n";
    }
    for (const std::string& headerPath : systemHeaderPaths) {
        if (std::find(registeredHeaderPaths.begin(), registeredHeaderPaths.end(), headerPath) ==
            registeredHeaderPaths.end()) {
            out << "#include \"" << headerPath << "\"\n";
        }
    }
    out << "\nnamespace Concord::Script {\n\n";
    out << "void RegisterAll(Concord::Scene& scene) {\n";
    for (const std::string& qualifiedName : registeredClasses) {
        out << "    scene.CreateEntity().Add<" << qualifiedName << ">();\n";
    }
    out << "}\n\nvoid AddSystems(Concord::Game& game) {\n";
    for (const std::string& qualifiedName : systemClasses) {
        out << "    game.Systems().Add<" << qualifiedName << ">();\n";
    }
    out << "}\n\n} // namespace Concord::Script\n";
    return out.str();
}

} // namespace ConcordScript
