cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED CONCORDC OR NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "CONCORDC and TEST_ROOT are required")
endif()
set(root "${TEST_ROOT}/cli")
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}/project" "${root}/empty")
file(WRITE "${root}/project/Main.cx" "@entry { return 0; };\n")

function(Run expected needle)
    execute_process(COMMAND "${CONCORDC}" --no-color ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "Expected ${expected}, got ${result}: ${ARGN}\n${output}\n${error}")
    endif()
    string(FIND "${output}${error}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing diagnostic '${needle}': ${output}${error}")
    endif()
endfunction()

Run(1 "missing value for --project" --project --out somewhere)
Run(1 "missing value for --out" --project "${root}/project" --out=)
Run(1 "duplicate option --project" --project "${root}" --project "${root}")
Run(1 "unknown CVM mode" --cvm=invalid)
Run(1 "mutually exclusive" --cpp --cvm)
Run(1 "does not accept a value" --help=true)
Run(1 "only apply" --cpp --no-run --project "${root}/project" --out "${root}/unused")
Run(1 "requires the C++ backend" --cvm --check --project "${root}/project")
Run(1 "no .cx source" --cpp --check --project "${root}/empty")
Run(0 "checked 1 file(s)" --project=${root}/project --cpp --check)
Run(0 "checked 1 file(s)" --project "${root}/project" --check --out "${root}/check-output")
if(EXISTS "${root}/check-output")
    message(FATAL_ERROR "--check wrote an output directory")
endif()

# UTF-8 BOM must not mask the first structural token; CRLF preserves line numbers.
string(ASCII 239 187 191 bom)
file(MAKE_DIRECTORY "${root}/bom")
file(WRITE "${root}/bom/Main.CX" "${bom}@entry { return 0; };\r\n// EOF comment")
Run(0 "checked 1 file(s)" --check --project "${root}/bom")
string(ASCII 255 254 utf16)
file(MAKE_DIRECTORY "${root}/utf16")
file(WRITE "${root}/utf16/Main.cx" "${utf16}x")
Run(1 "UTF-16 source" --check --project "${root}/utf16")

file(MAKE_DIRECTORY "${root}/malformed")
foreach(tail "/* unfinished" "\"unfinished" "'unfinished")
    file(WRITE "${root}/malformed/Main.cx" "@entry { return 0; };\n${tail}")
    Run(1 "Main.cx:2:" --check --project "${root}/malformed")
endforeach()

# Output/source nesting and common tool directories must not create extra entries.
file(MAKE_DIRECTORY "${root}/project/generated" "${root}/project/node_modules/pkg" "${root}/project/.git")
foreach(dir generated node_modules/pkg .git)
    file(WRITE "${root}/project/${dir}/Bad.cx" "@entry { return 1; };")
endforeach()
Run(0 "translated 1 file(s)" --project "${root}/project" --out=${root}/project/generated)
file(TIMESTAMP "${root}/project/generated/Main.gen.cpp" before "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
Run(0 "translated 1 file(s)" --project "${root}/project" --out "${root}/project/generated")
file(TIMESTAMP "${root}/project/generated/Main.gen.cpp" after "%s")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Unchanged generated C++ was rewritten")
endif()

# A directory occupying an output filename must become a diagnostic, not success.
file(MAKE_DIRECTORY "${root}/write-error/Main.gen.cpp")
Run(1 "cannot write output file" --project "${root}/bom" --out "${root}/write-error")
message(STATUS "CLI release regressions passed")

Run(0 "created project" --init "${root}/new game")
Run(0 "checked 1 file(s)" --project "${root}/new game" --check)
Run(1 "must be new or empty" --init "${root}/new game")
Run(1 "cannot be combined" --init "${root}/invalid-init" --cpp)
Run(1 "missing value for --init" --init)
if(EXISTS "${root}/invalid-init")
    message(FATAL_ERROR "Invalid init arguments created a directory")
endif()
file(READ "${root}/new game/Main.cx" starter)
string(FIND "${starter}" "@entry" entry)
if(entry EQUAL -1 OR NOT EXISTS "${root}/new game/CMakeLists.txt")
    message(FATAL_ERROR "Starter missing entry or build integration")
endif()
