# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Shared shader-tool discovery and command-line construction.  Keeping this
# logic in one helper makes bundled and ConcordScript-owned shaders behave the
# same way, including non-main entry points and HLSL inputs.

function(concord_resolve_shader_compiler out_compiler out_kind)
    set(prefer_hlsl FALSE)
    foreach(language IN LISTS ARGN)
        string(TOLOWER "${language}" language_lower)
        if(language_lower STREQUAL "hlsl")
            set(prefer_hlsl TRUE)
        endif()
    endforeach()

    set(compiler "${CONCORD_SHADER_COMPILER}")
    if(compiler AND NOT EXISTS "${compiler}")
        message(WARNING
            "Concord shader compiler not found: ${compiler}; probing PATH")
        find_program(resolved_compiler NAMES "${compiler}" NO_CACHE)
        set(compiler "${resolved_compiler}")
    endif()
    if(NOT compiler)
        if(prefer_hlsl)
            find_program(compiler NAMES glslangValidator dxc glslc NO_CACHE)
        else()
            find_program(compiler NAMES glslc glslangValidator dxc NO_CACHE)
        endif()
    endif()

    set(kind "")
    if(compiler)
        get_filename_component(compiler_name "${compiler}" NAME)
        string(TOLOWER "${compiler_name}" compiler_name)
        if(compiler_name MATCHES "glslangvalidator")
            set(kind glslang)
        elseif(compiler_name MATCHES "(^|[/\\])dxc(\\.exe)?$")
            set(kind dxc)
        elseif(compiler_name MATCHES "glslc")
            set(kind glslc)
        else()
            # Preserve support for project-local wrapper tools.  They follow
            # the glslc-compatible argument contract unless overridden by the
            # caller's own CMake rule.
            set(kind glslc)
        endif()
    endif()
    set(${out_compiler} "${compiler}" PARENT_SCOPE)
    set(${out_kind} "${kind}" PARENT_SCOPE)
endfunction()

function(concord_shader_profile stage out_profile)
    set(profile lib_6_3)
    if(stage STREQUAL vert)
        set(profile vs_6_0)
    elseif(stage STREQUAL tesc)
        set(profile hs_6_0)
    elseif(stage STREQUAL tese)
        set(profile ds_6_0)
    elseif(stage STREQUAL geom)
        set(profile gs_6_0)
    elseif(stage STREQUAL frag)
        set(profile ps_6_0)
    elseif(stage STREQUAL comp)
        set(profile cs_6_0)
    elseif(stage STREQUAL mesh)
        set(profile ms_6_5)
    elseif(stage STREQUAL task)
        set(profile as_6_5)
    endif()
    set(${out_profile} "${profile}" PARENT_SCOPE)
endfunction()

function(concord_normalize_shader_stage stage out_stage)
    string(TOLOWER "${stage}" value)
    if(value STREQUAL vertex OR value STREQUAL vs)
        set(value vert)
    elseif(value STREQUAL fragment OR value STREQUAL pixel OR value STREQUAL fs OR value STREQUAL ps)
        set(value frag)
    elseif(value STREQUAL compute OR value STREQUAL cs)
        set(value comp)
    elseif(value STREQUAL geometry OR value STREQUAL gs)
        set(value geom)
    elseif(value MATCHES "^(tess([_-]?control|ellation[_-]?control)|hull|hs)$")
        set(value tesc)
    elseif(value MATCHES "^(tess([_-]?eval|ellation[_-]?evaluation)|domain|ds)$")
        set(value tese)
    elseif(value MATCHES "^(ray[_-]?)?generation$" OR value STREQUAL raygen)
        set(value rgen)
    elseif(value MATCHES "^(ray[_-]?)?miss$" OR value STREQUAL miss)
        set(value rmiss)
    elseif(value MATCHES "^(ray[_-]?)?closest[_-]?hit$" OR value STREQUAL closesthit)
        set(value rchit)
    elseif(value MATCHES "^(ray[_-]?)?any[_-]?hit$" OR value STREQUAL anyhit)
        set(value rahit)
    elseif(value MATCHES "^(ray[_-]?)?intersection$" OR value STREQUAL intersection)
        set(value rint)
    elseif(value MATCHES "^(ray[_-]?)?callable$" OR value STREQUAL callable)
        set(value rcall)
    elseif(value MATCHES "^(task|amplification([_-]?shader)?|as)$")
        set(value task)
    elseif(value MATCHES "^(mesh([_-]?shader)?|ms)$")
        set(value mesh)
    endif()
    set(${out_stage} "${value}" PARENT_SCOPE)
endfunction()

function(concord_shader_arguments kind stage entry language out_arguments out_output_flag)
    string(TOLOWER "${language}" language_lower)
    set(arguments)
    if(kind STREQUAL glslang)
        set(arguments -V --target-env vulkan1.3 -S "${stage}" -e "${entry}")
        if(language_lower STREQUAL hlsl)
            list(APPEND arguments -D)
        endif()
        if(NOT entry STREQUAL main AND NOT language_lower STREQUAL hlsl)
            # glslang needs its source entry point to remain `main` while -e
            # selects the exported SPIR-V entry point. HLSL's -e already names
            # the source function, so it must not be rewritten to `main`.
            list(APPEND arguments --source-entrypoint main)
        endif()
        set(output_flag -o)
    elseif(kind STREQUAL dxc)
        if(NOT language_lower STREQUAL hlsl)
            message(FATAL_ERROR "DXC requires language=hlsl for ${stage} shader")
        endif()
        concord_shader_profile("${stage}" profile)
        set(arguments -spirv -fspv-target-env=vulkan1.3 -T "${profile}" -E "${entry}")
        set(output_flag -Fo)
    else()
        set(arguments --target-env=vulkan1.3 -fshader-stage=${stage})
        if(language_lower STREQUAL hlsl)
            list(APPEND arguments -x hlsl)
        endif()
        if(NOT entry STREQUAL main)
            list(APPEND arguments "-fentry-point=${entry}")
        endif()
        set(output_flag -o)
    endif()
    set(${out_arguments} "${arguments}" PARENT_SCOPE)
    set(${out_output_flag} "${output_flag}" PARENT_SCOPE)
endfunction()
